<x-guest-layout>
    <div class="mb-3"><span class="inline-flex rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-700 sm:text-xs">Nueva organización</span><h2 class="mt-2 text-2xl font-extrabold tracking-tight text-slate-950 sm:text-3xl">Crea tu espacio en CUMPLE</h2><p class="mt-1 text-xs leading-5 text-slate-500 sm:text-sm">Serás el administrador y después podrás crear áreas, usuarios y responsables.</p></div>
    <form method="POST" action="{{ route('register') }}" class="space-y-2.5">
        @csrf
        <div><x-input-label for="organization_name" value="Nombre de la organización"/><x-text-input id="organization_name" class="mt-1 block w-full" name="organization_name" :value="old('organization_name')" required autofocus autocomplete="organization" placeholder="Ejemplo: Koqoi Consultores"/><x-input-error :messages="$errors->get('organization_name')" class="mt-1"/></div>
        <div><x-input-label for="name" value="Tu nombre completo"/><x-text-input id="name" class="mt-1 block w-full" name="name" :value="old('name')" required autocomplete="name"/><x-input-error :messages="$errors->get('name')" class="mt-1"/></div>
        <div><x-input-label for="email" value="Correo de administración"/><x-text-input id="email" class="mt-1 block w-full" type="email" name="email" :value="old('email')" required autocomplete="username"/><x-input-error :messages="$errors->get('email')" class="mt-1"/></div>
        <div class="grid grid-cols-2 gap-2"><div class="min-w-0"><x-input-label for="password" value="Contraseña"/><x-text-input id="password" class="mt-1 block w-full" type="password" name="password" required autocomplete="new-password"/><x-input-error :messages="$errors->get('password')" class="mt-1"/></div><div class="min-w-0"><x-input-label for="password_confirmation" value="Confirmar"/><x-text-input id="password_confirmation" class="mt-1 block w-full" type="password" name="password_confirmation" required autocomplete="new-password"/></div></div>
        <label class="flex items-start gap-2 text-[11px] leading-4 text-slate-600 sm:text-xs"><input type="checkbox" name="terms" value="1" class="mt-0.5 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500" required><span>Acepto los <a class="font-bold text-emerald-700" href="{{ route('legal.terms') }}" target="_blank">términos</a>, la <a class="font-bold text-emerald-700" href="{{ route('legal.privacy') }}" target="_blank">privacidad</a> y el tratamiento de datos.</span></label><x-input-error :messages="$errors->get('terms')"/>
        <x-primary-button class="w-full py-2.5">Crear organización</x-primary-button>
        <p class="text-center text-xs text-slate-500 sm:text-sm">¿Ya tienes una cuenta? <a href="{{ route('login') }}" class="font-bold text-emerald-700">Ingresar</a></p>
    </form>
</x-guest-layout>
