<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-semibold text-emerald-700">Resumen de gestión</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-slate-900">Buenos días, {{ auth()->user()->name }}</h2></div><a href="{{ route('cases.index') }}" class="inline-flex items-center justify-center rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-800">Ver oportunidades</a></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        <div class="grid gap-3 grid-cols-2 lg:grid-cols-4">
            @foreach ([['Pendientes', $metrics['pending'], 'text-amber-800 bg-amber-50 ring-amber-200', ['status'=>'pending']], ['En ejecución', $metrics['in_progress'], 'text-emerald-800 bg-emerald-50 ring-emerald-200', ['status'=>'in_progress']], ['Por revisar', $metrics['in_review'], 'text-teal-800 bg-teal-50 ring-teal-200', ['status'=>'in_review']], ['Vencidas', $metrics['overdue'], 'text-rose-800 bg-rose-50 ring-rose-200', ['due'=>'overdue']]] as [$label, $value, $color, $filter])
                @if($value>0)<a href="{{ route('dashboard',$filter) }}" class="min-w-0 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:ring-emerald-300 sm:p-5"><div class="inline-flex max-w-full rounded-lg px-2.5 py-1 text-xs font-semibold ring-1 {{ $color }}">{{ $label }}</div><div class="mt-3 text-3xl font-extrabold tracking-tight text-slate-900 sm:text-4xl">{{ $value }}</div><p class="mt-1 text-xs font-semibold text-slate-400">Ver tareas</p></a>@endif
            @endforeach
        </div>

        @if($reviewTasks->isNotEmpty())
        <section class="rounded-2xl bg-teal-950 p-4 text-white shadow-sm sm:p-5"><div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-teal-200">Bandeja de aprobación</p><h3 class="mt-1 text-lg font-bold">Acciones que esperan tu revisión</h3></div><span class="rounded-full bg-white/10 px-3 py-1 text-sm font-bold ring-1 ring-white/20">{{ $reviewTasks->count() }}</span></div><div class="mt-4 grid gap-3 md:grid-cols-2">@foreach($reviewTasks as $task)<article class="min-w-0 rounded-xl bg-white/10 p-4 ring-1 ring-white/15"><p class="text-xs font-bold text-teal-200">{{ $task->improvementCase?->code ?? $task->code }}</p><p class="mt-1 break-words font-bold">{{ $task->title }}</p><p class="mt-2 text-xs text-teal-100">{{ $task->responsible_name }}</p><a href="{{ route('tasks.show',$task) }}" class="mt-3 inline-flex rounded-lg bg-white px-3 py-2 text-sm font-bold text-teal-950">Revisar acción</a></article>@endforeach</div></section>
        @endif

        <section class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-5">
            <div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h3 class="text-lg font-bold text-slate-900">Buscar y ejecutar tareas</h3><p class="mt-1 text-sm text-slate-500">Filtra tus acciones y abre la oportunidad para actualizar avance o cargar evidencias.</p></div><p class="text-sm font-semibold text-slate-500">{{ $taskResults->total() }} resultados</p></div>
            <form method="GET" action="{{ route('dashboard') }}" class="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-6">
                <div class="md:col-span-2 xl:col-span-2"><x-input-label for="q" value="Buscar"/><input id="q" name="q" value="{{ request('q') }}" placeholder="Tarea, código u oportunidad" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"></div>
                @if($taskStatuses->count()>1)<div><x-input-label for="status" value="Estado"/><select id="status" name="status" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"><option value="">Todos los estados</option>@foreach($taskStatuses as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ['pending'=>'Pendiente','in_progress'=>'En ejecución','in_review'=>'Por revisar','completed'=>'Completada','cancelled'=>'Cancelada'][$status] ?? $status }}</option>@endforeach</select></div>@endif
                @if($users->count()>1)<div><x-input-label for="assignee_id" value="Responsable"/><select id="assignee_id" name="assignee_id" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"><option value="">Todos los responsables</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)request('assignee_id')===(string)$user->id)>{{ $user->name }}</option>@endforeach</select></div>@endif
                @if($areas->count()>1)<div><x-input-label for="area_id" value="Área"/><select id="area_id" name="area_id" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"><option value="">Todas las áreas</option>@foreach($areas as $area)<option value="{{ $area->id }}" @selected((string)request('area_id')===(string)$area->id)>{{ $area->name }}</option>@endforeach</select></div>@endif
                @if($dueOptions->isNotEmpty())<div><x-input-label for="due" value="Fecha"/><select id="due" name="due" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"><option value="">Cualquier fecha</option>@foreach($dueOptions as $due)<option value="{{ $due }}" @selected(request('due')===$due)>{{ ['overdue'=>'Vencidas','next_7_days'=>'Próximos 7 días','no_date'=>'Sin fecha'][$due] }}</option>@endforeach</select></div>@endif
                <div class="flex flex-wrap items-center gap-3 md:col-span-2 xl:col-span-6"><x-primary-button>Aplicar filtros</x-primary-button>@if(request()->hasAny(['q','status','assignee_id','area_id','due']))<a href="{{ route('dashboard') }}" class="text-sm font-bold text-slate-600 hover:text-slate-900">Limpiar filtros</a>@endif</div>
            </form>
        </section>

        <div class="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_18rem]">
            <section class="min-w-0 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-5">
                <div class="space-y-3">@forelse($taskResults as $task)
                    @php($labels=['pending'=>'Pendiente','in_progress'=>'En ejecución','in_review'=>'Por revisar','completed'=>'Completada','cancelled'=>'Cancelada'])
                    <article class="min-w-0 rounded-2xl border border-slate-200 p-4 transition hover:border-emerald-300 hover:shadow-sm">
                        <div class="flex min-w-0 flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                            <div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold text-slate-600">{{ $task->improvementCase?->code ?? $task->code }}</span><span class="rounded-full px-2 py-1 text-[11px] font-bold {{ $task->status==='completed' ? 'bg-emerald-50 text-emerald-700' : ($task->due_at?->isPast() ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700') }}">{{ $labels[$task->status] ?? $task->status }}</span></div><h4 class="mt-3 break-words font-bold leading-6 text-slate-900">{{ $task->title }}</h4><p class="mt-2 break-words text-sm text-slate-600"><span class="font-semibold">Responsables:</span> {{ $task->responsible_name }}</p><p class="mt-1 text-xs text-slate-500">{{ $task->area?->name ?? 'Sin área' }} · {{ $task->progress }}% completado</p></div>
                            <div class="flex shrink-0 flex-row items-center justify-between gap-4 border-t border-slate-100 pt-3 lg:flex-col lg:items-end lg:border-0 lg:pt-0"><div class="lg:text-right"><p class="text-[11px] font-bold uppercase tracking-wide text-slate-400">Fecha límite</p><p class="mt-1 text-sm font-bold {{ $task->due_at?->isPast() && $task->status!=='completed' ? 'text-rose-700' : 'text-slate-700' }}">{{ $task->due_at?->format('d/m/Y') ?? 'Sin fecha' }}</p></div><a href="{{ route('tasks.show',$task) }}" class="rounded-xl bg-emerald-600 px-4 py-2 text-center text-sm font-bold text-white hover:bg-emerald-700">Abrir y ejecutar</a></div>
                        </div>
                    </article>
                @empty<div class="rounded-xl border border-dashed border-slate-300 p-10 text-center"><p class="font-semibold text-slate-700">No encontramos tareas con estos filtros.</p><a href="{{ route('dashboard') }}" class="mt-2 inline-block text-sm font-bold text-emerald-700">Mostrar todas</a></div>@endforelse</div>
                <div class="mt-5">{{ $taskResults->links() }}</div>
            </section>
            <aside class="rounded-2xl bg-emerald-950 p-5 text-white shadow-sm"><p class="text-sm font-semibold text-emerald-200">Control general</p><div class="mt-3 text-4xl font-extrabold">{{ $openCases }}</div><h3 class="mt-1 text-lg font-bold">oportunidades abiertas</h3><ol class="mt-5 space-y-3 text-sm leading-6 text-emerald-50/90"><li><span class="font-bold text-white">1.</span> Busca o filtra una tarea.</li><li><span class="font-bold text-white">2.</span> Pulsa “Abrir y ejecutar”.</li><li><span class="font-bold text-white">3.</span> Actualiza estado y avance.</li><li><span class="font-bold text-white">4.</span> Adjunta la evidencia correspondiente.</li></ol><a href="{{ route('cases.index') }}" class="mt-5 inline-flex rounded-xl bg-white/10 px-4 py-2 text-sm font-bold text-white ring-1 ring-white/20 hover:bg-white/20">Explorar oportunidades</a></aside>
        </div>
    </div></div>
</x-app-layout>
