<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-emerald-700">Configuración</p><h2 class="mt-1 text-2xl font-bold text-slate-900">Roles y aprobaciones</h2><p class="mt-1 text-sm text-slate-500">Define quién valida las acciones antes de su cierre.</p></div><a href="{{ route('administration.catalogs') }}" class="text-sm font-bold text-slate-600 hover:text-emerald-700">← Volver a configuración</a></div></x-slot>
    <div class="py-6 sm:py-8"><div class="mx-auto max-w-5xl space-y-5 px-4 sm:px-6 lg:px-8">
        @if(session('status'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800 ring-1 ring-emerald-200">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-sm text-rose-800 ring-1 ring-rose-200">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ route('approvals.update') }}" class="space-y-5">@csrf @method('PATCH')
            <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><h3 class="font-bold text-slate-900">Regla para cerrar una acción</h3><p class="mt-1 text-sm text-slate-500">Determina qué aprobación debe completarse después de entregar las evidencias.</p><div class="mt-5 grid gap-3 sm:grid-cols-3">@foreach(['both'=>['Calidad y Dirección Médica','Requiere las dos aprobaciones.'],'quality'=>['Solo Calidad','Calidad puede completar el cierre.'],'medical'=>['Solo Dirección Médica','Dirección Médica completa el cierre.']] as $value=>$option)<label class="cursor-pointer"><input type="radio" name="approval_policy" value="{{ $value }}" class="peer sr-only" @checked(old('approval_policy',$organization->approval_policy ?: 'both')===$value)><span class="block h-full rounded-xl border border-slate-200 p-4 peer-checked:border-emerald-500 peer-checked:bg-emerald-50"><strong class="block text-sm text-slate-900">{{ $option[0] }}</strong><small class="mt-1 block leading-5 text-slate-500">{{ $option[1] }}</small></span></label>@endforeach</div></section>
            <div class="grid gap-5 lg:grid-cols-2">@foreach(['quality'=>['Aprobadores de Calidad','Usuarios autorizados para revisar en nombre de Calidad.'],'medical'=>['Aprobadores de Dirección Médica','Usuarios autorizados para revisar en nombre de Dirección Médica.']] as $type=>$copy) @php($selected=$type==='quality'?$qualityApproverIds:$medicalApproverIds)<section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 class="font-bold text-slate-900">{{ $copy[0] }}</h3><p class="mt-1 text-sm leading-6 text-slate-500">{{ $copy[1] }}</p><div class="mt-4 max-h-80 space-y-2 overflow-y-auto rounded-xl border border-slate-200 p-2">@foreach($users as $user)<label class="flex cursor-pointer items-start gap-3 rounded-lg p-3 hover:bg-slate-50"><input type="checkbox" name="{{ $type }}_approver_ids[]" value="{{ $user->id }}" class="mt-0.5 rounded border-slate-300 text-emerald-600" @checked(in_array($user->id,old($type.'_approver_ids',$selected->all())))><span class="min-w-0"><strong class="block truncate text-sm text-slate-800">{{ $user->name }}</strong><small class="block truncate text-xs text-slate-500">{{ $user->role_label }}{{ $user->area ? ' · '.$user->area->name : '' }}</small></span></label>@endforeach</div></section>@endforeach</div>
            <div class="flex justify-end"><x-primary-button>Guardar flujo de aprobación</x-primary-button></div>
        </form>
    </div></div>
</x-app-layout>
