<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-emerald-700">Configuración</p><h2 class="mt-1 text-2xl font-bold text-slate-900">Áreas y servicios</h2></div><a href="{{ route('administration.catalogs') }}" class="text-sm font-bold text-slate-600 hover:text-emerald-700">← Volver a configuración</a></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-5xl space-y-5 px-4 sm:px-6 lg:px-8">
        @if(session('status'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800 ring-1 ring-emerald-200">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-sm text-rose-800 ring-1 ring-rose-200">{{ $errors->first() }}</div>@endif
        <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><div class="flex items-start justify-between gap-4"><div><h3 class="text-lg font-bold">Nueva área o servicio</h3><p class="mt-1 text-sm text-slate-500">Crea la unidad y, si corresponde, asigna su coordinador.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{{ $areas->count() }} áreas</span></div><form method="POST" action="{{ route('areas.store') }}" class="mt-5 grid gap-4 sm:grid-cols-2">@csrf<div><x-input-label value="Nombre"/><input name="name" class="mt-1 block w-full rounded-xl border-slate-300" required></div><div><x-input-label value="Coordinador responsable"/><select name="coordinator_id" class="mt-1 block w-full rounded-xl border-slate-300"><option value="">Sin coordinador</option>@foreach($coordinators as $user)<option value="{{ $user->id }}">{{ $user->name }} · {{ $user->role_label }}</option>@endforeach</select></div><div class="sm:col-span-2"><x-input-label value="Descripción (opcional)"/><textarea name="description" rows="2" class="mt-1 block w-full rounded-xl border-slate-300"></textarea></div><div class="sm:col-span-2"><x-primary-button>Agregar área o servicio</x-primary-button></div></form></section>
        <section class="space-y-3" x-data="{ editing: null }">@forelse($areas as $area)<article class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div class="flex items-start gap-4"><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h3 class="font-bold text-slate-900">{{ $area->name }}</h3><span class="rounded-full px-2 py-1 text-[11px] font-bold {{ $area->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $area->is_active ? 'Activa' : 'Inactiva' }}</span></div><p class="mt-2 text-sm text-slate-600">Coordinador: <span class="font-semibold">{{ $area->coordinator?->name ?? 'Sin asignar' }}</span></p>@if($area->description)<p class="mt-1 text-sm text-slate-500">{{ $area->description }}</p>@endif</div><button type="button" @click="editing=editing==={{ $area->id }}?null:{{ $area->id }}" class="rounded-lg bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-700">Editar</button></div><div x-show="editing==={{ $area->id }}" x-collapse x-cloak class="mt-4 border-t border-slate-100 pt-4"><form method="POST" action="{{ route('areas.update',$area) }}" class="grid gap-3 sm:grid-cols-2">@csrf @method('PATCH')<div><x-input-label value="Nombre"/><input name="name" value="{{ $area->name }}" class="mt-1 block w-full rounded-xl border-slate-300" required></div><div><x-input-label value="Coordinador"/><select name="coordinator_id" class="mt-1 block w-full rounded-xl border-slate-300"><option value="">Sin coordinador</option>@foreach($coordinators as $user)<option value="{{ $user->id }}" @selected($area->coordinator_id==$user->id)>{{ $user->name }} · {{ $user->role_label }}</option>@endforeach</select></div><div><x-input-label value="Descripción"/><textarea name="description" rows="2" class="mt-1 block w-full rounded-xl border-slate-300">{{ $area->description }}</textarea></div><div><x-input-label value="Estado"/><select name="is_active" class="mt-1 block w-full rounded-xl border-slate-300"><option value="1" @selected($area->is_active)>Activa</option><option value="0" @selected(!$area->is_active)>Inactiva</option></select></div><div class="sm:col-span-2"><x-secondary-button type="submit">Guardar cambios</x-secondary-button></div></form><form method="POST" action="{{ route('areas.destroy',$area) }}" class="mt-4 border-t border-rose-100 pt-3" onsubmit="return confirm('¿Eliminar esta área?')">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-700">Eliminar esta área</button><p class="mt-1 text-xs text-slate-500">Solo es posible si no tiene registros asociados.</p></form></div></article>@empty<div class="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500">Aún no hay áreas configuradas.</div>@endforelse</section>
    </div></div>
</x-app-layout>
