<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-semibold text-emerald-700">Administración</p><h2 class="mt-1 text-2xl font-bold text-slate-900">Configuración</h2></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        @if(session('status'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800 ring-1 ring-emerald-200">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-sm text-rose-800 ring-1 ring-rose-200">{{ $errors->first() }}</div>@endif
        <div class="grid items-start gap-6 lg:grid-cols-2">
            <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200" x-data="{ editing: null }">
                <div class="flex items-start justify-between gap-4"><div><h3 class="text-lg font-bold">Áreas y servicios</h3><p class="mt-1 text-sm text-slate-500">Crea las áreas y asigna aquí mismo su coordinador responsable.</p></div><span class="shrink-0 rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{{ $areas->count() }} áreas</span></div>
                <form method="POST" action="{{ route('areas.store') }}" class="mt-5 grid gap-4 rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-200 sm:grid-cols-2">@csrf
                    <div><x-input-label value="Nombre del área"/><input name="name" class="mt-1 block w-full rounded-xl border-slate-300" required></div>
                    <div><x-input-label value="Coordinador responsable"/><select name="coordinator_id" class="mt-1 block w-full rounded-xl border-slate-300"><option value="">Sin coordinador por ahora</option>@foreach($coordinators as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div>
                    <div class="sm:col-span-2"><x-input-label value="Descripción (opcional)"/><textarea name="description" rows="2" class="mt-1 block w-full rounded-xl border-slate-300" placeholder="Ejemplo: servicios o alcance que pertenecen a esta área"></textarea></div>
                    <div class="sm:col-span-2"><x-primary-button>Agregar área o servicio</x-primary-button></div>
                </form>
                <div class="mt-5 space-y-3">@foreach($areas as $area)<article class="rounded-xl border border-slate-200 p-4"><div class="flex gap-3"><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><p class="font-bold text-slate-900">{{ $area->name }}</p><span class="rounded-full px-2 py-1 text-[11px] font-bold {{ $area->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $area->is_active ? 'Activa' : 'Inactiva' }}</span></div><p class="mt-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Coordinador responsable</p><p class="mt-1 text-sm font-semibold {{ $area->coordinator ? 'text-slate-800' : 'text-amber-700' }}">{{ $area->coordinator?->name ?? 'Pendiente de asignar' }}</p>@if($area->description)<p class="mt-2 text-xs leading-5 text-slate-500">{{ $area->description }}</p>@endif</div><button type="button" @click="editing=editing==={{ $area->id }}?null:{{ $area->id }}" class="self-start rounded-lg bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-700">Editar</button></div>
                    <form x-show="editing==={{ $area->id }}" x-collapse x-cloak method="POST" action="{{ route('areas.update',$area) }}" class="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-2">@csrf @method('PATCH')
                        <div><x-input-label value="Nombre del área"/><input name="name" value="{{ $area->name }}" class="mt-1 block w-full rounded-xl border-slate-300" required></div><div><x-input-label value="Coordinador responsable"/><select name="coordinator_id" class="mt-1 block w-full rounded-xl border-slate-300"><option value="">Sin coordinador</option>@foreach($coordinators as $user)<option value="{{ $user->id }}" @selected($area->coordinator_id==$user->id)>{{ $user->name }}</option>@endforeach</select></div>
                        <div><x-input-label value="Descripción (opcional)"/><textarea name="description" rows="2" class="mt-1 block w-full rounded-xl border-slate-300">{{ $area->description }}</textarea></div><div><x-input-label value="Estado del área"/><select name="is_active" class="mt-1 block w-full rounded-xl border-slate-300"><option value="1" @selected($area->is_active)>Activa</option><option value="0" @selected(!$area->is_active)>Inactiva</option></select></div><div class="sm:col-span-2"><x-secondary-button type="submit">Guardar cambios</x-secondary-button></div>
                    </form><form x-show="editing==={{ $area->id }}" x-cloak method="POST" action="{{ route('areas.destroy',$area) }}" class="mt-3 border-t border-rose-100 pt-3" onsubmit="return confirm('¿Eliminar el área {{ addslashes($area->name) }}? Esta acción no se puede deshacer.')">@csrf @method('DELETE')<button type="submit" class="text-sm font-bold text-rose-700 hover:text-rose-900">Eliminar esta área</button><p class="mt-1 text-xs text-slate-500">Solo podrá eliminarse si no tiene tareas ni hallazgos asociados.</p></form></article>@endforeach</div>
            </section>
            <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200" x-data="{ editing: null }">
                <h3 class="text-lg font-bold">Fuentes de hallazgos</h3><p class="mt-1 text-sm text-slate-500">Define de dónde provienen las oportunidades de mejora.</p>
                <form method="POST" action="{{ route('sources.store') }}" class="mt-5 grid gap-4 sm:grid-cols-2">@csrf<div><x-input-label value="Nombre de la fuente"/><input name="name" class="mt-1 block w-full rounded-xl border-slate-300" required></div><div><x-input-label value="Tipo de análisis"/><select name="is_invima" class="mt-1 block w-full rounded-xl border-slate-300"><option value="0">General</option><option value="1">INVIMA</option></select></div><div class="sm:col-span-2"><x-primary-button>Crear fuente</x-primary-button></div></form>
                <div class="mt-6 divide-y divide-slate-100">@foreach($sources as $source)<article class="py-4"><div class="flex items-center justify-between gap-3"><div><p class="font-bold text-slate-900">{{ $source->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $source->is_invima ? 'INVIMA · análisis causa–efecto' : 'Análisis general' }} · {{ $source->is_active ? 'Activa' : 'Inactiva' }}</p></div><button type="button" @click="editing=editing==={{ $source->id }}?null:{{ $source->id }}" class="rounded-lg bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-700">Editar</button></div>
                    <form x-show="editing==={{ $source->id }}" x-collapse x-cloak method="POST" action="{{ route('sources.update',$source) }}" class="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-2">@csrf @method('PATCH')<div class="sm:col-span-2"><x-input-label value="Nombre de la fuente"/><input name="name" value="{{ $source->name }}" class="mt-1 block w-full rounded-xl border-slate-300" required></div><div><x-input-label value="Tipo de análisis"/><select name="is_invima" class="mt-1 block w-full rounded-xl border-slate-300"><option value="0" @selected(!$source->is_invima)>General</option><option value="1" @selected($source->is_invima)>INVIMA</option></select></div><div><x-input-label value="Estado"/><select name="is_active" class="mt-1 block w-full rounded-xl border-slate-300"><option value="1" @selected($source->is_active)>Activa</option><option value="0" @selected(!$source->is_active)>Inactiva</option></select></div><div class="sm:col-span-2"><x-secondary-button type="submit">Guardar cambios</x-secondary-button></div></form>
                </article>@endforeach</div>
            </section>
        </div>
    </div></div>
</x-app-layout>
