<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-semibold text-emerald-700">Administración</p><h2 class="mt-1 text-2xl font-bold text-slate-900">Configuración</h2><p class="mt-1 text-sm text-slate-500">Selecciona el módulo que deseas administrar.</p></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">
            <a href="{{ route('administration.organization') }}" class="group rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:shadow-md hover:ring-emerald-300"><div class="flex items-start justify-between gap-4"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-100 text-2xl">🏢</span><span class="text-xl text-slate-300 transition group-hover:translate-x-1 group-hover:text-emerald-600">→</span></div><h3 class="mt-5 text-lg font-bold text-slate-900">Organización</h3><p class="mt-1 text-sm font-semibold text-emerald-700">{{ $organization?->name }}</p><p class="mt-3 text-sm leading-6 text-slate-500">Administra la identidad visible de este espacio de trabajo.</p></a>
            <a href="{{ route('administration.areas') }}" class="group rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:shadow-md hover:ring-emerald-300"><div class="flex items-start justify-between gap-4"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-100 text-2xl">▦</span><span class="text-xl text-slate-300 transition group-hover:translate-x-1 group-hover:text-emerald-600">→</span></div><h3 class="mt-5 text-lg font-bold text-slate-900">Áreas y servicios</h3><p class="mt-1 text-sm font-semibold text-emerald-700">{{ $areaCount }} registrados</p><p class="mt-3 text-sm leading-6 text-slate-500">Crea áreas, define su estado y asigna coordinadores.</p></a>
            <a href="{{ route('administration.sources') }}" class="group rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:shadow-md hover:ring-emerald-300"><div class="flex items-start justify-between gap-4"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-100 text-2xl">◎</span><span class="text-xl text-slate-300 transition group-hover:translate-x-1 group-hover:text-emerald-600">→</span></div><h3 class="mt-5 text-lg font-bold text-slate-900">Fuentes de hallazgos</h3><p class="mt-1 text-sm font-semibold text-emerald-700">{{ $sourceCount }} configuradas</p><p class="mt-3 text-sm leading-6 text-slate-500">Organiza los posibles orígenes de las oportunidades de mejora.</p></a>
            <div class="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-white text-2xl text-slate-400 ring-1 ring-slate-200">＋</span><h3 class="mt-5 text-lg font-bold text-slate-700">Más configuraciones</h3><p class="mt-3 text-sm leading-6 text-slate-500">Este espacio queda preparado para integraciones, plantillas y reglas futuras.</p></div>
        </div>
    </div></div>
</x-app-layout>
