<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-emerald-700">Configuración</p><h2 class="mt-1 text-2xl font-bold text-slate-900">Recordatorios y alertas</h2><p class="mt-1 text-sm text-slate-500">Define cuándo CUMPLE debe avisar a responsables y aprobadores.</p></div><a href="{{ route('administration.catalogs') }}" class="text-sm font-bold text-slate-600 hover:text-emerald-700">← Volver a configuración</a></div></x-slot>
    <div class="py-6 sm:py-8"><div class="mx-auto max-w-4xl space-y-5 px-4 sm:px-6 lg:px-8">
        @if(session('status'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800 ring-1 ring-emerald-200">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-sm text-rose-800 ring-1 ring-rose-200">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ route('reminders.update') }}" class="space-y-5">@csrf @method('PATCH')
            <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><div class="flex items-start gap-4"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-emerald-100 text-xl text-emerald-700">◷</span><div class="min-w-0 flex-1"><h3 class="font-bold text-slate-900">Avisos antes del vencimiento</h3><p class="mt-1 text-sm leading-6 text-slate-500">Se envían una sola vez a todos los responsables internos de cada acción.</p><div class="mt-5"><input type="hidden" name="reminders_enabled" value="0"><label class="flex items-center gap-3 text-sm font-bold text-slate-700"><input type="checkbox" name="reminders_enabled" value="1" @checked(old('reminders_enabled',$organization->reminders_enabled)) class="rounded border-slate-300 text-emerald-600 focus:ring-emerald-500">Activar recordatorios automáticos</label></div><div class="mt-5"><p class="text-sm font-semibold text-slate-700">Días de anticipación</p><div class="mt-3 flex flex-wrap gap-2">@foreach([30,14,7,3,1] as $day)<label class="cursor-pointer"><input type="checkbox" name="reminder_days[]" value="{{ $day }}" class="peer sr-only" @checked(in_array($day,old('reminder_days',$organization->reminder_days ?: [7,3,1])))><span class="inline-flex rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold text-slate-600 peer-checked:border-emerald-500 peer-checked:bg-emerald-50 peer-checked:text-emerald-700">{{ $day }} {{ $day===1 ? 'día' : 'días' }}</span></label>@endforeach</div></div></div></div></section>
            <section class="grid gap-4 sm:grid-cols-2"><label class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><input type="hidden" name="overdue_alerts_enabled" value="0"><div class="flex items-start gap-3"><input type="checkbox" name="overdue_alerts_enabled" value="1" @checked(old('overdue_alerts_enabled',$organization->overdue_alerts_enabled)) class="mt-1 rounded border-slate-300 text-rose-600 focus:ring-rose-500"><div><h3 class="font-bold text-slate-900">Avisar cuando venza</h3><p class="mt-1 text-sm leading-6 text-slate-500">Notifica al responsable el primer día de vencimiento.</p></div></div></label><label class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><input type="hidden" name="review_alerts_enabled" value="0"><div class="flex items-start gap-3"><input type="checkbox" name="review_alerts_enabled" value="1" @checked(old('review_alerts_enabled',$organization->review_alerts_enabled)) class="mt-1 rounded border-slate-300 text-violet-600 focus:ring-violet-500"><div><h3 class="font-bold text-slate-900">Avisar a los aprobadores</h3><p class="mt-1 text-sm leading-6 text-slate-500">Notifica a Calidad y Dirección Médica cuando una acción espera revisión.</p></div></div></label></section>
            <div class="flex justify-end"><x-primary-button>Guardar configuración</x-primary-button></div>
        </form>
    </div></div>
</x-app-layout>
