<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-emerald-700">Configuración</p><h2 class="mt-1 text-2xl font-bold text-slate-900">Fuentes de hallazgos</h2></div><a href="{{ route('administration.catalogs') }}" class="text-sm font-bold text-slate-600 hover:text-emerald-700">← Volver a configuración</a></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-5xl space-y-5 px-4 sm:px-6 lg:px-8">
        @if(session('status'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800 ring-1 ring-emerald-200">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-sm text-rose-800 ring-1 ring-rose-200">{{ $errors->first() }}</div>@endif
        <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><div class="flex items-start justify-between gap-4"><div><h3 class="text-lg font-bold">Nueva fuente</h3><p class="mt-1 text-sm text-slate-500">Define de dónde pueden originarse las oportunidades de mejora.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{{ $sources->count() }} fuentes</span></div><form method="POST" action="{{ route('sources.store') }}" class="mt-5 grid gap-4 sm:grid-cols-2">@csrf<div><x-input-label value="Nombre de la fuente"/><input name="name" class="mt-1 block w-full rounded-xl border-slate-300" required></div><div><x-input-label value="Tipo de análisis"/><select name="is_invima" class="mt-1 block w-full rounded-xl border-slate-300"><option value="0">General</option><option value="1">INVIMA</option></select></div><div class="sm:col-span-2"><x-primary-button>Crear fuente</x-primary-button></div></form></section>
        <section class="divide-y divide-slate-100 rounded-2xl bg-white px-5 shadow-sm ring-1 ring-slate-200 sm:px-6" x-data="{ editing: null }">@forelse($sources as $source)<article class="py-5"><div class="flex items-center justify-between gap-3"><div><div class="flex flex-wrap items-center gap-2"><h3 class="font-bold text-slate-900">{{ $source->name }}</h3><span class="rounded-full px-2 py-1 text-[11px] font-bold {{ $source->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $source->is_active ? 'Activa' : 'Inactiva' }}</span></div><p class="mt-1 text-xs text-slate-500">{{ $source->is_invima ? 'INVIMA · análisis causa–efecto' : 'Análisis general' }}</p></div><button type="button" @click="editing=editing==={{ $source->id }}?null:{{ $source->id }}" class="rounded-lg bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-700">Editar</button></div><form x-show="editing==={{ $source->id }}" x-collapse x-cloak method="POST" action="{{ route('sources.update',$source) }}" class="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-2">@csrf @method('PATCH')<div class="sm:col-span-2"><x-input-label value="Nombre"/><input name="name" value="{{ $source->name }}" class="mt-1 block w-full rounded-xl border-slate-300" required></div><div><x-input-label value="Tipo de análisis"/><select name="is_invima" class="mt-1 block w-full rounded-xl border-slate-300"><option value="0" @selected(!$source->is_invima)>General</option><option value="1" @selected($source->is_invima)>INVIMA</option></select></div><div><x-input-label value="Estado"/><select name="is_active" class="mt-1 block w-full rounded-xl border-slate-300"><option value="1" @selected($source->is_active)>Activa</option><option value="0" @selected(!$source->is_active)>Inactiva</option></select></div><div class="sm:col-span-2"><x-secondary-button type="submit">Guardar cambios</x-secondary-button></div></form></article>@empty<div class="py-10 text-center text-sm text-slate-500">Aún no hay fuentes configuradas.</div>@endforelse</section>
    </div></div>
</x-app-layout>
