<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-emerald-700">{{ $minute->number }}</p><h2 class="mt-1 text-2xl font-bold">Organizar tareas propuestas</h2><p class="mt-1 text-sm text-slate-500">Edita, asigna o elimina varios compromisos de Kairo en una sola pantalla.</p></div><a href="{{ route('minutes.show',$minute) }}" class="text-sm font-bold text-slate-600">← Volver al acta</a></div></x-slot>
    <div class="py-6 sm:py-8"><div class="mx-auto max-w-7xl space-y-5 px-4 sm:px-6 lg:px-8">
        @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-sm text-rose-800 ring-1 ring-rose-200">{{ $errors->first() }}</div>@endif
        @if($minute->commitmentProposals->isEmpty())<div class="rounded-2xl bg-white p-10 text-center text-slate-500 shadow-sm ring-1 ring-slate-200">No quedan propuestas pendientes.</div>@else
        <form x-data="{ selected: @js($minute->commitmentProposals->pluck('id')->values()) }" method="POST" action="{{ route('minutes.proposals.bulk.process',$minute) }}" class="space-y-4">@csrf
            <div class="sticky top-2 z-20 flex flex-col gap-3 rounded-2xl bg-slate-950 p-4 text-white shadow-xl sm:flex-row sm:items-center sm:justify-between"><div><strong>Procesamiento masivo</strong><p class="text-xs text-slate-300"><span x-text="selected.length"></span> propuestas seleccionadas</p></div><div class="flex flex-col gap-2 sm:flex-row"><button type="button" @click="selected = selected.length ? [] : @js($minute->commitmentProposals->pluck('id')->values())" class="rounded-xl border border-slate-600 px-3 py-2 text-sm font-bold">Seleccionar / limpiar todas</button><button name="action" value="dismiss" onclick="return confirm('¿Eliminar las propuestas seleccionadas?')" class="rounded-xl bg-rose-700 px-4 py-2 text-sm font-bold">Eliminar seleccionadas</button><button name="action" value="convert" class="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold">Crear tareas seleccionadas</button></div></div>
            @foreach($minute->commitmentProposals as $proposal)
                @php
                    $normalized = \Illuminate\Support\Str::lower(\Illuminate\Support\Str::ascii(trim((string)$proposal->suggested_responsible)));
                    $matchedUser = $users->first(fn($user) => \Illuminate\Support\Str::lower(\Illuminate\Support\Str::ascii(trim($user->name))) === $normalized);
                    $type = $matchedUser ? 'internal' : 'external';
                    $date = preg_match('/^(\d{2})\/(\d{2})\/(\d{4})$/', (string)$proposal->suggested_due_date, $parts) ? "{$parts[3]}-{$parts[2]}-{$parts[1]}" : '';
                @endphp
                <article x-data="{ type: '{{ $type }}' }" class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-5"><div class="mb-4 flex items-start gap-3"><input x-model.number="selected" name="selected[]" value="{{ $proposal->id }}" type="checkbox" class="mt-1 rounded text-emerald-700"><div><p class="text-xs font-bold uppercase text-amber-700">Propuesta {{ $loop->iteration }}</p><p class="mt-1 text-xs text-slate-500">Kairo sugirió: {{ $proposal->suggested_responsible ?: 'sin responsable' }} · {{ $proposal->suggested_due_date ?: 'sin fecha' }}</p></div></div><div class="grid gap-4 lg:grid-cols-12">
                    <div class="lg:col-span-7"><x-input-label value="Tarea"/><input name="proposals[{{ $proposal->id }}][title]" value="{{ $proposal->title }}" class="mt-1 block w-full rounded-xl border-slate-300"></div>
                    <div class="lg:col-span-3"><x-input-label value="Área"/><select name="proposals[{{ $proposal->id }}][area_id]" class="mt-1 block w-full rounded-xl border-slate-300"><option value="">Selecciona</option>@foreach($areas as $area)<option value="{{ $area->id }}" @selected($minute->area_id===$area->id)>{{ $area->name }}</option>@endforeach</select></div>
                    <div class="lg:col-span-2"><x-input-label value="Fecha límite"/><input name="proposals[{{ $proposal->id }}][due_at]" type="date" value="{{ $date }}" class="mt-1 block w-full rounded-xl border-slate-300"></div>
                    <div class="lg:col-span-6"><x-input-label value="Evidencia esperada"/><textarea name="proposals[{{ $proposal->id }}][expected_result]" rows="3" class="mt-1 block w-full rounded-xl border-slate-300" placeholder="Soporte esperado para demostrar cumplimiento"></textarea></div>
                    <div class="grid gap-4 lg:col-span-6 sm:grid-cols-2"><div><x-input-label value="Tipo de responsable"/><select name="proposals[{{ $proposal->id }}][assignee_type]" x-model="type" class="mt-1 block w-full rounded-xl border-slate-300"><option value="internal">Usuarios CUMPLE</option><option value="external">Externo</option></select></div><div x-show="type==='external'"><x-input-label value="Responsable externo"/><input name="proposals[{{ $proposal->id }}][external_assignee_name]" value="{{ $proposal->suggested_responsible }}" class="mt-1 block w-full rounded-xl border-slate-300"></div><div x-show="type==='internal'" class="sm:col-span-2"><x-input-label value="Responsables CUMPLE"/><select name="proposals[{{ $proposal->id }}][assignee_ids][]" multiple size="3" class="mt-1 block w-full rounded-xl border-slate-300">@foreach($users as $user)<option value="{{ $user->id }}" @selected($matchedUser?->id===$user->id)>{{ $user->name }} · {{ $user->role_label }}</option>@endforeach</select></div></div>
                </div></article>
            @endforeach
        </form>
        @endif
    </div></div>
</x-app-layout>
