<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div class="min-w-0"><p class="text-sm font-semibold text-emerald-700">{{ $task->code }}</p><h2 class="mt-1 break-words text-2xl font-bold">Ejecutar acción</h2></div><a href="{{ route('dashboard') }}" class="text-sm font-bold text-slate-600">Volver a mis tareas</a></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-6xl space-y-6 px-4 sm:px-6 lg:px-8">
        @if(session('status'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800 ring-1 ring-emerald-200">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-sm text-rose-800 ring-1 ring-rose-200">{{ $errors->first() }}</div>@endif
        <section class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div class="min-w-0"><h3 class="break-words text-lg font-bold">{{ $task->title }}</h3><p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600">{{ $task->description }}</p><p class="mt-3 text-sm"><span class="font-bold">Responsables:</span> {{ $task->responsible_name }}</p></div><div class="shrink-0 rounded-xl bg-slate-50 px-4 py-3 text-sm ring-1 ring-slate-200"><p class="text-xs font-bold uppercase text-slate-400">Fecha límite</p><p class="mt-1 font-bold">{{ $task->due_at?->format('d/m/Y') ?? 'Sin fecha' }}</p></div></div></section>
        <section class="rounded-2xl bg-amber-50 p-4 ring-1 ring-amber-200 sm:p-5"><p class="text-xs font-bold uppercase text-amber-800">Evidencia esperada</p><p class="mt-2 whitespace-pre-line text-sm leading-6 text-amber-950">{{ $task->expected_result ?: 'No se definió una evidencia específica.' }}</p></section>
        <div class="grid gap-6 lg:grid-cols-2">
            <section class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-5"><h3 class="font-bold">Estado y avance</h3><form method="POST" action="{{ route('tasks.update',$task) }}" class="mt-4 space-y-4" x-data="{ progress: {{ (int) $task->progress }}, status: '{{ $task->status }}' }">@csrf @method('PATCH')<select name="status" x-model="status" class="w-full rounded-xl border-slate-300" @disabled($task->status==='completed')>@foreach(['pending'=>'Sin inicio','in_progress'=>'En proceso','in_review'=>'Finalicé: enviar a revisión','cancelled'=>'Cancelada'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach @if($task->status==='completed')<option selected value="completed">Cerrada</option>@endif</select><div><div class="mb-2 flex items-center justify-between text-sm"><span class="font-semibold text-slate-700">Porcentaje de cumplimiento</span><output class="rounded-lg bg-emerald-50 px-2 py-1 font-bold text-emerald-800" x-text="status === 'in_review' ? '100 %' : progress + ' %'"></output></div><input name="progress" type="range" min="0" max="100" step="5" x-model="progress" :value="status === 'in_review' ? 100 : progress" class="w-full accent-emerald-600" @disabled($task->status==='completed')></div><textarea name="review_notes" rows="3" class="block w-full rounded-xl border-slate-300" placeholder="Nota de seguimiento" @disabled($task->status==='completed')>{{ $task->review_notes }}</textarea>@if($task->status!=='completed')<x-secondary-button type="submit">Actualizar seguimiento</x-secondary-button>@endif</form><p class="mt-3 text-xs leading-5 text-slate-500">Al seleccionar “Finalicé”, el avance pasa a 100 % y se envía a aprobación. Si se devuelve, regresará al 90 % con la causal.</p></section>
            <section class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-5"><h3 class="font-bold">Evidencias realizadas</h3><form method="POST" enctype="multipart/form-data" action="{{ route('tasks.evidence.store',$task) }}" class="mt-4 space-y-3">@csrf<input name="evidence" type="file" class="block w-full max-w-full text-sm" required><input name="description" class="block w-full rounded-xl border-slate-300" placeholder="Descripción de la evidencia"><x-secondary-button type="submit">Adjuntar evidencia</x-secondary-button></form><div class="mt-4 space-y-2">@forelse($task->evidences as $evidence)<a href="{{ route('evidence.download',$evidence) }}" class="block truncate rounded-lg bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-800">{{ $evidence->original_name }}</a>@empty<p class="text-sm text-slate-500">Todavía no hay evidencias.</p>@endforelse</div></section>
        </div>
        <section class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-5"><h3 class="font-bold">Aprobaciones para el cierre</h3><div class="mt-3 flex flex-wrap gap-2"><span class="rounded-full px-3 py-1 text-xs font-bold {{ $task->quality_approved_at ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800' }}">Calidad: {{ $task->quality_approved_at ? 'Aprobada por '.$task->qualityApprover?->name : 'Pendiente' }}</span><span class="rounded-full px-3 py-1 text-xs font-bold {{ $task->medical_approved_at ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800' }}">Dirección Médica: {{ $task->medical_approved_at ? 'Aprobada por '.$task->medicalApprover?->name : 'Pendiente' }}</span></div>
            @if($task->status==='in_review' && ($canReviewAsQuality || $canReviewAsMedicalDirectorate))<div class="mt-5 grid max-w-2xl gap-3 sm:grid-cols-[1fr_auto]"><form method="POST" action="{{ route('tasks.review',$task) }}" class="space-y-3">@csrf @method('PATCH')<input type="hidden" name="decision" value="reject"><textarea name="review_notes" rows="2" required class="block w-full rounded-xl border-slate-300" placeholder="Causal obligatoria de devolución"></textarea><button class="w-full rounded-xl border border-rose-200 px-4 py-2 text-sm font-bold text-rose-700">Devolver y notificar</button></form><form method="POST" action="{{ route('tasks.review',$task) }}" class="self-end">@csrf @method('PATCH')<input type="hidden" name="decision" value="approve"><button class="w-full rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Registrar mi aprobación</button></form></div>@endif
        </section>
    </div></div>
</x-app-layout>
