<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-semibold text-emerald-700">Nuevo expediente</p><h2 class="mt-1 text-2xl font-bold text-slate-900">Registrar hallazgo</h2></div></x-slot>
    <div class="py-10"><div class="mx-auto max-w-4xl px-4 sm:px-6"><form method="POST" action="{{ route('cases.store') }}" class="space-y-6">@csrf
        <section class="rounded-2xl bg-emerald-950 p-6 text-white"><p class="font-bold">Herramienta de apoyo y seguimiento</p><p class="mt-2 text-sm leading-6 text-emerald-100">Este registro no sustituye el reporte institucional. Conserva el Excel o Word original para su envío a Gestión de Calidad.</p></section>
        <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h3 class="text-lg font-bold">Información del reporte</h3><div class="mt-6 grid gap-5 sm:grid-cols-2">
            <div class="sm:col-span-2"><x-input-label for="title" value="Título corto"/><x-text-input id="title" name="title" value="{{ old('title') }}" class="mt-1 block w-full" required/><x-input-error :messages="$errors->get('title')" class="mt-1"/></div>
            <div><x-input-label for="reported_at" value="Fecha del reporte"/><x-text-input id="reported_at" name="reported_at" type="date" value="{{ old('reported_at', now()->toDateString()) }}" class="mt-1 block w-full" required/></div>
            <div><x-input-label for="action_type" value="Tipo de acción"/><select id="action_type" name="action_type" class="mt-1 block w-full rounded-xl border-slate-300"><option value="improvement">Acción de mejora</option><option value="corrective">Acción correctiva</option></select></div>
            <div class="sm:col-span-2"><x-input-label for="finding_source_id" value="Fuente que origina el hallazgo"/><select id="finding_source_id" name="finding_source_id" class="mt-1 block w-full rounded-xl border-slate-300" required><option value="">Seleccione…</option>@foreach($sources as $source)<option value="{{ $source->id }}" @selected(old('finding_source_id')==$source->id)>{{ $source->name }}</option>@endforeach</select></div>
            <div><x-input-label for="reporting_area_id" value="Área que reporta"/><select id="reporting_area_id" name="reporting_area_id" class="mt-1 block w-full rounded-xl border-slate-300" required><option value="">Seleccione…</option>@foreach($areas as $area)<option value="{{ $area->id }}">{{ $area->name }}</option>@endforeach</select></div>
            <div><x-input-label for="reported_area_id" value="Área reportada (si aplica)"/><select id="reported_area_id" name="reported_area_id" class="mt-1 block w-full rounded-xl border-slate-300"><option value="">No aplica</option>@foreach($areas as $area)<option value="{{ $area->id }}">{{ $area->name }}</option>@endforeach</select></div>
            <div class="sm:col-span-2"><x-input-label for="finding_description" value="Descripción del hallazgo"/><textarea id="finding_description" name="finding_description" rows="7" class="mt-1 block w-full rounded-xl border-slate-300" required>{{ old('finding_description') }}</textarea><x-input-error :messages="$errors->get('finding_description')" class="mt-1"/></div>
        </div></section>
        <div class="flex justify-end gap-3"><a href="{{ route('cases.index') }}" class="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Cancelar</a><x-primary-button>Guardar y continuar</x-primary-button></div>
    </form></div></div>
</x-app-layout>
