<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-semibold text-emerald-700">Nuevo expediente</p><h2 class="mt-1 text-2xl font-bold text-slate-900">Registrar hallazgo</h2></div></x-slot>
    <div class="py-10"><div class="mx-auto max-w-4xl space-y-6 px-4 sm:px-6">
        @php($import = session('excel_import', []))
        <section class="rounded-2xl bg-emerald-950 p-6 text-white"><p class="font-bold">Herramienta de apoyo y seguimiento</p><p class="mt-2 text-sm leading-6 text-emerald-100">Este registro no sustituye el reporte institucional. Conserva el Excel o Word original para su envío a Gestión de Calidad.</p></section>
        <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex flex-wrap items-start justify-between gap-4"><div><h3 class="text-lg font-bold">Importar Excel institucional</h3><p class="mt-1 max-w-2xl text-sm text-slate-500">CUMPLE leerá automáticamente las celdas conocidas. No utiliza IA y no modifica el archivo original.</p></div>@if($import)<span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800">Archivo reconocido</span>@endif</div>
            @if($errors->has('excel'))<div class="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{{ $errors->first('excel') }}</div>@endif
            <div class="mt-4 flex flex-wrap items-center gap-3"><form method="POST" enctype="multipart/form-data" action="{{ route('cases.import') }}" class="flex flex-wrap items-center gap-3">@csrf<input name="excel" type="file" accept=".xlsx,.xls" class="block text-sm" required><x-secondary-button>Leer Excel</x-secondary-button></form>@if($import)<p class="text-sm text-slate-600">{{ $import['original_name'] }}</p>@endif</div>
            @if($import && (!$import['finding_source_id'] || !$import['reporting_area_id']))<p class="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Se importaron los datos, pero debes seleccionar manualmente {{ !$import['finding_source_id'] ? 'la fuente' : '' }}{{ !$import['finding_source_id'] && !$import['reporting_area_id'] ? ' y ' : '' }}{{ !$import['reporting_area_id'] ? 'el área que reporta' : '' }} porque el nombre del Excel no coincide con el catálogo actual.</p>@endif
        </section>
        <form method="POST" action="{{ route('cases.store') }}" class="space-y-6">@csrf
        @if($import)
            <input type="hidden" name="temporary_path" value="{{ $import['temporary_path'] }}"><input type="hidden" name="original_name" value="{{ $import['original_name'] }}">
            @foreach(['institutional_consecutive','reported_person_name','reported_person_position','urgency_score','scope_score','evolution_score','priority_score','analysis_method'] as $field)<input type="hidden" name="{{ $field }}" value="{{ $import[$field] ?? '' }}">@endforeach
        @endif
        <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h3 class="text-lg font-bold">Información del reporte</h3><div class="mt-6 grid gap-5 sm:grid-cols-2">
            <div class="sm:col-span-2"><x-input-label for="title" value="Título corto"/><x-text-input id="title" name="title" value="{{ old('title',$import['title'] ?? '') }}" class="mt-1 block w-full" required/><x-input-error :messages="$errors->get('title')" class="mt-1"/></div>
            <div><x-input-label for="reported_at" value="Fecha del reporte"/><x-text-input id="reported_at" name="reported_at" type="date" value="{{ old('reported_at',$import['reported_at'] ?? now()->toDateString()) }}" class="mt-1 block w-full" required/></div>
            <div><x-input-label for="action_type" value="Tipo de acción"/><select id="action_type" name="action_type" class="mt-1 block w-full rounded-xl border-slate-300"><option value="improvement" @selected(old('action_type',$import['action_type'] ?? '')==='improvement')>Acción de mejora</option><option value="corrective" @selected(old('action_type',$import['action_type'] ?? '')==='corrective')>Acción correctiva</option></select></div>
            <div class="sm:col-span-2"><x-input-label for="finding_source_id" value="Fuente que origina el hallazgo"/><select id="finding_source_id" name="finding_source_id" class="mt-1 block w-full rounded-xl border-slate-300" required><option value="">Seleccione…</option>@foreach($sources as $source)<option value="{{ $source->id }}" @selected(old('finding_source_id',$import['finding_source_id'] ?? null)==$source->id)>{{ $source->name }}</option>@endforeach</select></div>
            <div><x-input-label for="reporting_area_id" value="Área que reporta"/><select id="reporting_area_id" name="reporting_area_id" class="mt-1 block w-full rounded-xl border-slate-300" required><option value="">Seleccione…</option>@foreach($areas as $area)<option value="{{ $area->id }}" @selected(old('reporting_area_id',$import['reporting_area_id'] ?? null)==$area->id)>{{ $area->name }}</option>@endforeach</select></div>
            <div><x-input-label for="reported_area_id" value="Área reportada (si aplica)"/><select id="reported_area_id" name="reported_area_id" class="mt-1 block w-full rounded-xl border-slate-300"><option value="">No aplica</option>@foreach($areas as $area)<option value="{{ $area->id }}" @selected(old('reported_area_id',$import['reported_area_id'] ?? null)==$area->id)>{{ $area->name }}</option>@endforeach</select></div>
            <div class="sm:col-span-2"><x-input-label for="finding_description" value="Descripción del hallazgo"/><textarea id="finding_description" name="finding_description" rows="7" class="mt-1 block w-full rounded-xl border-slate-300" required>{{ old('finding_description',$import['finding_description'] ?? '') }}</textarea><x-input-error :messages="$errors->get('finding_description')" class="mt-1"/></div>
        </div></section>
        <div class="flex justify-end gap-3"><a href="{{ route('cases.index') }}" class="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Cancelar</a><x-primary-button>Guardar y continuar</x-primary-button></div>
        </form>
    </div></div>
</x-app-layout>
