<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-semibold text-emerald-700">Portafolio de mejora</p><h2 class="mt-1 text-2xl font-bold text-slate-900">Hallazgos y planes</h2></div><a href="{{ route('cases.create') }}" class="inline-flex items-center justify-center rounded-xl bg-emerald-700 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-800">Registrar hallazgo</a></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        <section class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-5">
            <div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h3 class="text-lg font-bold text-slate-900">Buscar oportunidades</h3><p class="mt-1 text-sm text-slate-500">Consulta el portafolio por origen, tipo, estado, área o responsable.</p></div><p class="text-sm font-semibold text-slate-500">{{ $cases->total() }} resultados</p></div>
            <form method="GET" action="{{ route('cases.index') }}" class="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-6">
                <div class="md:col-span-2 xl:col-span-2"><x-input-label for="q" value="Oportunidad o código"/><input id="q" name="q" value="{{ request('q') }}" placeholder="Ejemplo: ACR-MA4 o seguridad" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"></div>
                <div><x-input-label for="source_id" value="Origen"/><select id="source_id" name="source_id" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"><option value="">Todos</option>@foreach($sources as $source)<option value="{{ $source->id }}" @selected((string)request('source_id')===(string)$source->id)>{{ $source->name }}</option>@endforeach</select></div>
                <div><x-input-label for="action_type" value="Tipo"/><select id="action_type" name="action_type" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"><option value="">Todos</option><option value="improvement" @selected(request('action_type')==='improvement')>Oportunidad de mejora</option><option value="corrective" @selected(request('action_type')==='corrective')>Acción correctiva</option></select></div>
                <div><x-input-label for="status" value="Estado del plan"/><select id="status" name="status" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"><option value="">Todos</option>@foreach(['draft'=>'Borrador','analysis'=>'En análisis','action_plan'=>'Plan de acción','closed'=>'Cerrado','cancelled'=>'Cancelado'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></div>
                <div><x-input-label for="area_id" value="Área que reporta"/><select id="area_id" name="area_id" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"><option value="">Todas</option>@foreach($areas as $area)<option value="{{ $area->id }}" @selected((string)request('area_id')===(string)$area->id)>{{ $area->name }}</option>@endforeach</select></div>
                <div class="md:col-span-2 xl:col-span-2"><x-input-label for="assignee_id" value="Responsable de alguna acción"/><select id="assignee_id" name="assignee_id" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"><option value="">Todos</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)request('assignee_id')===(string)$user->id)>{{ $user->name }}</option>@endforeach</select></div>
                <div class="flex flex-wrap items-end gap-3 md:col-span-2 xl:col-span-4"><x-primary-button>Aplicar filtros</x-primary-button>@if(request()->hasAny(['q','source_id','action_type','status','area_id','assignee_id']))<a href="{{ route('cases.index') }}" class="pb-2 text-sm font-bold text-slate-600">Limpiar filtros</a>@endif</div>
            </form>
        </section>

        <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            @forelse($cases as $case)
                @php($statuses=['draft'=>'Borrador','analysis'=>'En análisis','action_plan'=>'Plan de acción','closed'=>'Cerrado','cancelled'=>'Cancelado'])
                <article class="flex min-w-0 flex-col rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 transition hover:ring-emerald-300">
                    <div class="flex flex-wrap items-center justify-between gap-2"><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-800">{{ $case->code }}</span><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{{ $statuses[$case->status] ?? $case->status }}</span></div>
                    <h3 class="mt-4 break-words font-bold leading-6 text-slate-900">{{ $case->title }}</h3><p class="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{{ $case->finding_description }}</p>
                    <dl class="mt-4 space-y-2 border-t border-slate-100 pt-4 text-sm"><div class="flex gap-2"><dt class="w-20 shrink-0 font-semibold text-slate-500">Origen</dt><dd class="min-w-0 break-words text-slate-700">{{ $case->source->name }}</dd></div><div class="flex gap-2"><dt class="w-20 shrink-0 font-semibold text-slate-500">Tipo</dt><dd class="text-slate-700">{{ $case->action_type==='corrective' ? 'Acción correctiva' : 'Oportunidad de mejora' }}</dd></div><div class="flex gap-2"><dt class="w-20 shrink-0 font-semibold text-slate-500">Acciones</dt><dd class="font-bold text-slate-800">{{ $case->tasks_count }}</dd></div></dl>
                    <a href="{{ route('cases.show',$case) }}" class="mt-5 inline-flex justify-center rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-emerald-700">Abrir oportunidad</a>
                </article>
            @empty<div class="rounded-2xl border border-dashed border-slate-300 p-12 text-center text-slate-500 md:col-span-2 xl:col-span-3">No encontramos oportunidades con estos filtros.</div>@endforelse
        </section>
        <div>{{ $cases->links() }}</div>
    </div></div>
</x-app-layout>
