<x-app-layout>
    <x-slot name="header"><div class="flex items-start justify-between gap-4"><div><p class="text-sm font-semibold text-emerald-700">{{ $case->code }}</p><h2 class="mt-1 text-2xl font-bold text-slate-900">{{ $case->title }}</h2></div><a href="{{ route('cases.index') }}" class="text-sm font-semibold text-slate-600">Volver al listado</a></div></x-slot>
    <div class="py-10"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        @if(session('status'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800 ring-1 ring-emerald-200">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-sm text-rose-800 ring-1 ring-rose-200"><p class="font-bold">Revisa los campos indicados:</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        @php
            $executionOnly = str_starts_with($case->code, 'ACR-');
            $responsibleOptions = $users->map(fn($user) => ['id'=>$user->id, 'name'=>$user->name, 'area'=>$user->area?->name])->values();
            $newActionAssigneeIds = collect(old('assignee_ids', []))->map(fn($id) => (int) $id)->values();
            $analysisMethodLabel = match (true) {
                $case->source->is_invima => 'Causa–efecto · obligatorio para fuentes INVIMA',
                $case->priority_score === null => 'Se calculará al guardar la priorización',
                $case->priority_score > 4 => 'Causa–efecto · puntaje mayor de 4',
                default => 'Cinco porqués · puntaje de 4 o menos',
            };
        @endphp
        <div class="grid gap-6 lg:grid-cols-[1.15fr_.85fr]">
            <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="grid gap-5 sm:grid-cols-2"><div><p class="text-xs font-semibold uppercase text-slate-500">Fuente</p><p class="mt-1 font-semibold">{{ $case->source->name }}</p></div><div><p class="text-xs font-semibold uppercase text-slate-500">Tipo</p><p class="mt-1">{{ $case->action_type === 'corrective' ? 'Acción correctiva' : 'Acción de mejora' }}</p></div><div><p class="text-xs font-semibold uppercase text-slate-500">Área que reporta</p><p class="mt-1">{{ $case->reportingArea->name }}</p></div><div><p class="text-xs font-semibold uppercase text-slate-500">Fecha</p><p class="mt-1">{{ $case->reported_at->format('d/m/Y') }}</p></div><div class="sm:col-span-2"><p class="text-xs font-semibold uppercase text-slate-500">Descripción</p><p class="mt-2 whitespace-pre-line leading-7 text-slate-700">{{ $case->finding_description }}</p></div></div></section>
            <aside class="rounded-2xl bg-emerald-950 p-6 text-white"><p class="text-sm font-semibold text-emerald-200">Documento institucional</p><h3 class="mt-2 text-lg font-bold">El original continúa siendo oficial</h3><p class="mt-3 text-sm leading-6 text-emerald-100">CUMPLE conserva el archivo recibido sin cambios y genera copias de trabajo con el análisis, las acciones, responsables, fechas y evidencias esperadas.</p>@unless($executionOnly)<form method="POST" action="{{ route('cases.documents.generate',$case) }}" class="mt-5">@csrf<button class="w-full rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-emerald-950 hover:bg-emerald-50">Generar copia de trabajo Excel</button></form>@endunless</aside>
        </div>
        @unless($executionOnly)<div class="grid gap-6 lg:grid-cols-2">
            <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex items-start justify-between gap-4"><div><h3 class="text-lg font-bold">Documentos institucionales</h3><p class="mt-1 text-sm text-slate-500">El original se conserva sin modificaciones.</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-700">{{ $case->documents->count() }} archivos</span></div>
                <div class="mt-5 space-y-2">@foreach($case->documents as $document)<div class="flex items-center justify-between rounded-xl border border-slate-200 p-3"><div class="min-w-0"><p class="truncate text-sm font-semibold">{{ $document->original_name }}</p><p class="text-xs text-slate-500">{{ ['original'=>'Original recibido','working'=>'Copia de trabajo','final'=>'Versión preparada'][$document->document_stage] ?? $document->document_stage }} · {{ number_format($document->size / 1024, 0) }} KB</p></div><a href="{{ route('documents.download',$document) }}" class="ml-3 text-sm font-bold text-emerald-700">Descargar</a></div>@endforeach</div>
                <form method="POST" enctype="multipart/form-data" action="{{ route('cases.documents.store',$case) }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf
                    <div class="sm:col-span-2"><x-input-label for="file" value="Adjuntar Word, Excel o PDF"/><input id="file" name="file" type="file" accept=".xlsx,.xls,.docx,.doc,.pdf" class="mt-1 block w-full text-sm" required></div>
                    <select name="document_stage" class="rounded-xl border-slate-300 text-sm"><option value="original">Original recibido</option><option value="working">Copia de trabajo</option><option value="final">Versión preparada para enviar</option></select>
                    <select name="document_type" class="rounded-xl border-slate-300 text-sm"><option value="finding_report">Reporte y plan de acción</option><option value="nonconformity">No conforme</option><option value="minutes">Acta</option><option value="other">Otro</option></select>
                    <div class="sm:col-span-2 flex justify-end"><x-secondary-button type="submit">Guardar documento</x-secondary-button></div>
                </form>
            </section>
            <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h3 class="text-lg font-bold">Priorización y validación</h3><p class="mt-1 text-sm text-slate-500">Solo se habilitará un método de análisis. INVIMA utiliza siempre causa–efecto.</p>
                <form method="POST" action="{{ route('cases.prioritization.update',$case) }}" class="mt-5 grid gap-4 sm:grid-cols-3">@csrf @method('PATCH')
                    @foreach(['urgency_score'=>'Urgencia','scope_score'=>'Alcance','evolution_score'=>'Evolución'] as $field=>$label)<div><x-input-label :for="$field" :value="$label"/><input id="{{ $field }}" name="{{ $field }}" type="number" min="0" max="10" value="{{ old($field,$case->$field) }}" class="mt-1 block w-full rounded-xl border-slate-300" required></div>@endforeach
                    <div class="sm:col-span-3 rounded-xl bg-slate-50 p-4 ring-1 ring-slate-200"><p class="text-xs font-bold uppercase tracking-wide text-slate-500">Método determinado automáticamente</p><p class="mt-1 font-bold text-emerald-800">{{ $analysisMethodLabel }}</p><p class="mt-1 text-xs text-slate-500">El método no se selecciona manualmente; depende del puntaje total.</p></div>
                    <div class="sm:col-span-3"><x-input-label for="validation_notes" value="Observaciones de validación"/><textarea id="validation_notes" name="validation_notes" rows="2" class="mt-1 block w-full rounded-xl border-slate-300">{{ old('validation_notes',$case->validation_notes) }}</textarea></div>
                    <div class="sm:col-span-3 flex items-center justify-between"><p class="text-sm text-slate-600">Puntaje: <strong>{{ $case->priority_score ?? 'Pendiente' }}</strong></p><x-secondary-button type="submit">Guardar priorización</x-secondary-button></div>
                </form>
            </section>
        </div>@endunless
        @if($case->analysis_method)
        <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div><p class="text-sm font-semibold text-emerald-700">Método seleccionado</p><h3 class="mt-1 text-lg font-bold">{{ $case->analysis_method === 'five_whys' ? 'Análisis de los cinco por qué' : 'Análisis de causa–efecto' }}</h3></div>
            @if($executionOnly)<div class="mt-5 space-y-3">@forelse(data_get($case->analysis_data,'whys',[]) as $index=>$why)<div class="rounded-xl bg-slate-50 p-4 ring-1 ring-slate-200"><p class="text-xs font-bold uppercase text-emerald-700">{{ $index + 1 }}. ¿Por qué?</p><p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-700">{{ $why }}</p></div>@empty<p class="text-sm text-slate-500">La matriz no contiene pasos causales diligenciados.</p>@endforelse<div class="rounded-xl bg-emerald-50 p-4 ring-1 ring-emerald-200"><p class="text-xs font-bold uppercase text-emerald-800">Causa raíz identificada</p><p class="mt-2 whitespace-pre-line text-sm leading-6 text-emerald-950">{{ $case->root_cause ?: 'Sin causa raíz registrada' }}</p></div></div>@else
            <form method="POST" action="{{ route('cases.analysis.update',$case) }}" class="mt-6 space-y-5">@csrf @method('PATCH')
                <div><x-input-label for="immediate_correction" value="Acción inmediata o corrección"/><textarea id="immediate_correction" name="immediate_correction" rows="3" class="mt-1 block w-full rounded-xl border-slate-300">{{ old('immediate_correction',$case->immediate_correction) }}</textarea></div>
                @if($case->analysis_method === 'five_whys')
                    <div class="grid gap-3">@for($i=0;$i<5;$i++)<div><x-input-label :for="'why_'.$i" :value="($i+1).'. ¿Por qué?'"/><textarea id="why_{{ $i }}" name="whys[]" rows="2" class="mt-1 block w-full rounded-xl border-slate-300" required>{{ old('whys.'.$i, data_get($case->analysis_data,'whys.'.$i)) }}</textarea></div>@endfor</div>
                @else
                    @php
                        $causeOptions=['personal'=>'Personal, habilidad o técnica','protocols'=>'Adherencia a protocolos o guías','communication'=>'Comunicación, atención o conocimiento','equipment'=>'Equipos y tecnología','resources'=>'Recursos e insumos','procedures'=>'Procedimientos y documentación','environment'=>'Entorno e infraestructura','measurement'=>'Supervisión, medición e indicadores'];
                        $savedCauses=collect(data_get($case->analysis_data,'causes',[]))->keyBy('id');
                        $legacyCategories=collect(data_get($case->analysis_data,'categories',[]));
                        $selectedCauseIds=old('cause_categories',$savedCauses->keys()->merge(collect($causeOptions)->filter(fn($label)=>$legacyCategories->contains($label))->keys())->unique()->values()->all());
                    @endphp
                    <div x-data="{ selected: @js($selectedCauseIds) }"><x-input-label value="Categorías relacionadas y causa identificada"/><p class="mt-1 text-xs text-slate-500">Selecciona una categoría y describe específicamente qué causa encontraste en ella.</p><div class="mt-3 grid gap-3 sm:grid-cols-2">@foreach($causeOptions as $id=>$category)<article class="rounded-xl border p-4 transition" :class="selected.includes('{{ $id }}') ? 'border-emerald-300 bg-emerald-50/50' : 'border-slate-200'"><label class="flex items-start gap-3 text-sm font-semibold text-slate-800"><input x-model="selected" type="checkbox" name="cause_categories[]" value="{{ $id }}" class="mt-0.5 rounded border-slate-300 text-emerald-700"><span>{{ $category }}</span></label><div x-show="selected.includes('{{ $id }}')" x-collapse class="mt-3"><x-input-label :for="'cause_'.$id" value="Causa encontrada"/><textarea id="cause_{{ $id }}" name="cause_descriptions[{{ $id }}]" rows="3" :required="selected.includes('{{ $id }}')" class="mt-1 block w-full rounded-xl border-slate-300 text-sm" placeholder="Describe la causa correspondiente a esta categoría">{{ old('cause_descriptions.'.$id,data_get($savedCauses->get($id),'description',data_get($case->analysis_data,'description'))) }}</textarea></div></article>@endforeach</div></div>
                @endif
                <div><x-input-label for="root_cause" value="Causa raíz consolidada"/><textarea id="root_cause" name="root_cause" rows="3" class="mt-1 block w-full rounded-xl border-slate-300" required>{{ old('root_cause',$case->root_cause) }}</textarea></div>
                <div class="flex justify-end"><x-primary-button>Guardar análisis</x-primary-button></div>
            </form>@endif
        </section>
        @endif
        <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex items-center justify-between"><div><h3 class="text-lg font-bold">Acciones del plan</h3><p class="mt-1 text-sm text-slate-500">{{ $executionOnly ? 'Selecciona responsables, actualiza el avance y adjunta las evidencias.' : 'Cada acción puede asignarse a uno o varios usuarios CUMPLE.' }}</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-sm font-bold text-emerald-800">{{ $case->tasks->count() }}</span></div>
            <div class="mt-5 space-y-3">@forelse($case->tasks as $task)<article id="task-{{ $task->id }}" x-data="{ open: window.location.hash === '#task-{{ $task->id }}' }" class="scroll-mt-24 rounded-xl border border-slate-200 p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div class="min-w-0 flex-1"><p class="font-bold text-slate-900">{{ $task->title }}</p><p class="mt-1 text-sm text-slate-600">Responsables: <span class="font-semibold">{{ $task->responsible_name }}</span></p></div><div class="text-right"><p class="text-xs uppercase text-slate-500">Fecha límite</p><p class="font-semibold {{ $task->due_at?->isPast() && $task->status!=='completed' ? 'text-rose-700' : 'text-slate-800' }}">{{ $task->due_at?->format('d/m/Y') }}</p><button @click="open=!open" type="button" class="mt-2 text-xs font-bold text-emerald-700">{{ $executionOnly ? 'Trabajar acción' : 'Seguimiento y evidencias' }}</button></div></div>
                <div x-show="open" x-cloak class="mt-4 space-y-5 border-t border-slate-100 pt-4"><div class="grid gap-4 md:grid-cols-2"><div><p class="text-xs font-bold uppercase text-slate-500">Acción definida</p><p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-700">{{ $task->description ?: $task->title }}</p></div><div class="rounded-xl bg-amber-50 p-4 ring-1 ring-amber-200"><p class="text-xs font-bold uppercase text-amber-800">Evidencia esperada</p><p class="mt-2 whitespace-pre-line text-sm leading-6 text-amber-950">{{ $task->expected_result ?: 'No se definió una evidencia específica.' }}</p></div></div><div class="grid gap-5 xl:grid-cols-3">
                @php($currentAssigneeIds = $task->assignees->pluck('id')->whenEmpty(fn($ids) => $task->assigned_to ? collect([$task->assigned_to]) : collect())->map(fn($id) => (int) $id)->values())
                <form method="POST" action="{{ route('tasks.assignees.update',$task) }}" class="space-y-3" x-data="{ type: '{{ $task->assignee_type }}', candidate: '', selected: @js($currentAssigneeIds), people: @js($responsibleOptions), add() { const id=Number(this.candidate); if(id && !this.selected.includes(id)) this.selected.push(id); this.candidate=''; }, person(id) { return this.people.find(person=>person.id===id) } }">@csrf @method('PATCH')<p class="text-sm font-bold text-slate-800">Responsables de la acción</p><select name="assignee_type" x-model="type" class="w-full rounded-xl border-slate-300 text-sm"><option value="internal">Usuarios CUMPLE</option><option value="external">Responsable externo</option></select><div x-show="type==='internal'" class="space-y-2"><div class="flex gap-2"><select x-model="candidate" class="min-w-0 flex-1 rounded-xl border-slate-300 text-sm"><option value="">Selecciona…</option><template x-for="person in people" :key="person.id"><option :value="person.id" x-text="person.name"></option></template></select><button type="button" @click="add" class="rounded-xl bg-emerald-700 px-3 text-sm font-bold text-white">Agregar</button></div><div class="flex flex-wrap gap-2"><template x-for="id in selected" :key="id"><span class="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800"><input type="hidden" name="assignee_ids[]" :value="id"><span x-text="person(id)?.name"></span><button type="button" @click="selected=selected.filter(item=>item!==id)">×</button></span></template></div></div><div x-show="type==='external'" class="space-y-2"><input name="external_assignee_name" value="{{ $task->external_assignee_name }}" x-bind:required="type==='external'" class="block w-full rounded-xl border-slate-300 text-sm" placeholder="Nombre del responsable externo"><input name="external_assignee_email" value="{{ $task->external_assignee_email }}" type="email" class="block w-full rounded-xl border-slate-300 text-sm" placeholder="Correo externo (opcional)"></div><x-secondary-button type="submit">Guardar responsables</x-secondary-button></form>
                <form method="POST" action="{{ route('tasks.update',$task) }}" class="space-y-3" x-data="{ progress: {{ (int) $task->progress }}, status: '{{ $task->status }}' }">@csrf @method('PATCH')<p class="text-sm font-bold text-slate-800">Estado y avance</p><select name="status" x-model="status" class="w-full rounded-xl border-slate-300 text-sm" @disabled($task->status==='completed')>@foreach(['pending'=>'Sin inicio','in_progress'=>'En proceso','in_review'=>'Finalicé: enviar a revisión','cancelled'=>'Cancelada'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach @if($task->status==='completed')<option value="completed" selected>Cerrada</option>@endif</select><div><div class="mb-1 flex justify-between text-xs font-semibold text-slate-600"><span>Cumplimiento</span><output x-text="status === 'in_review' ? '100 %' : progress + ' %'"></output></div><input name="progress" type="range" min="0" max="100" step="5" x-model="progress" :value="status === 'in_review' ? 100 : progress" class="w-full accent-emerald-600" @disabled($task->status==='completed')></div><textarea name="review_notes" rows="3" class="block w-full rounded-xl border-slate-300 text-sm" placeholder="Nota de seguimiento" @disabled($task->status==='completed')>{{ $task->review_notes }}</textarea>@if($task->status!=='completed')<x-secondary-button type="submit">Actualizar seguimiento</x-secondary-button>@endif<p class="text-xs leading-5 text-slate-500">“Finalicé” pasa a 100 %. Si se devuelve, regresa al 90 % y recibirás la causal.</p></form>
                <div><form method="POST" enctype="multipart/form-data" action="{{ route('tasks.evidence.store',$task) }}" class="space-y-3">@csrf<p class="text-sm font-bold text-slate-800">Evidencias realizadas</p><input name="evidence" type="file" class="block w-full max-w-full text-sm" required><input name="description" class="block w-full rounded-xl border-slate-300 text-sm" placeholder="Descripción de la evidencia"><x-secondary-button type="submit">Adjuntar evidencia</x-secondary-button></form><div class="mt-3 space-y-1">@foreach($task->evidences as $evidence)<a href="{{ route('evidence.download',$evidence) }}" class="block truncate text-sm font-semibold text-emerald-700">{{ $evidence->original_name }}</a>@endforeach</div></div></div>
                <section class="rounded-xl bg-slate-50 p-4 ring-1 ring-slate-200"><div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p class="text-sm font-bold text-slate-800">Aprobaciones para el cierre</p><div class="mt-3 flex flex-wrap gap-2"><span class="rounded-full px-3 py-1 text-xs font-bold {{ !$requiresQuality ? 'bg-slate-100 text-slate-500' : ($task->quality_approved_at ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800') }}">Calidad: {{ !$requiresQuality ? 'No requerida' : ($task->quality_approved_at ? 'Aprobada por '.$task->qualityApprover?->name : 'Pendiente') }}</span><span class="rounded-full px-3 py-1 text-xs font-bold {{ !$requiresMedical ? 'bg-slate-100 text-slate-500' : ($task->medical_approved_at ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800') }}">Dirección Médica: {{ !$requiresMedical ? 'No requerida' : ($task->medical_approved_at ? 'Aprobada por '.$task->medicalApprover?->name : 'Pendiente') }}</span></div>@if($task->review_notes)<p class="mt-3 text-sm text-slate-600"><span class="font-bold">Observaciones:</span> {{ $task->review_notes }}</p>@endif</div>
                @if($task->status==='in_review' && ($canReviewAsQuality || $canReviewAsMedicalDirectorate))<div class="w-full space-y-3 lg:max-w-md"><form method="POST" action="{{ route('tasks.review',$task) }}" class="space-y-2">@csrf @method('PATCH')<input type="hidden" name="decision" value="reject"><textarea name="review_notes" rows="2" required class="block w-full rounded-xl border-slate-300 text-sm" placeholder="Causal obligatoria de devolución"></textarea><button class="w-full rounded-xl border border-rose-200 bg-white px-4 py-2 text-sm font-bold text-rose-700">Devolver y notificar</button></form><form method="POST" action="{{ route('tasks.review',$task) }}">@csrf @method('PATCH')<input type="hidden" name="decision" value="approve"><button class="w-full rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Registrar mi aprobación</button></form></div>@endif</div></section></div>
            </article>@empty<div class="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">Aún no se han agregado acciones.</div>@endforelse</div>
        </section>
        @if(!$executionOnly && $case->root_cause && $case->tasks->isNotEmpty())
        <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-sm font-semibold text-emerald-700">Seguimiento 2</p><h3 class="mt-1 text-lg font-bold">Verificación de la eficacia</h3><p class="mt-1 text-sm text-slate-500">Si el plan no fue eficaz, permanecerá abierto para agregar nuevas acciones.</p></div>@if($case->closed_at)<span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800">Cerrado {{ $case->closed_at->format('d/m/Y') }}</span>@endif</div>
            @if(in_array(auth()->user()->role,['administrator','quality']) || auth()->user()->isCoordinator())<form method="POST" action="{{ route('cases.effectiveness.update',$case) }}" class="mt-6 grid gap-5 sm:grid-cols-2">@csrf @method('PATCH')
                <div><x-input-label for="impact_before" value="Impacto antes del plan"/><textarea id="impact_before" name="impact_before" rows="3" class="mt-1 block w-full rounded-xl border-slate-300" required>{{ old('impact_before',$case->impact_before) }}</textarea></div>
                <div><x-input-label for="impact_after" value="Impacto después del plan"/><textarea id="impact_after" name="impact_after" rows="3" class="mt-1 block w-full rounded-xl border-slate-300" required>{{ old('impact_after',$case->impact_after) }}</textarea></div>
                <div class="sm:col-span-2"><x-input-label for="effectiveness_result" value="Resultado de la verificación"/><textarea id="effectiveness_result" name="effectiveness_result" rows="3" class="mt-1 block w-full rounded-xl border-slate-300" required>{{ old('effectiveness_result',$case->effectiveness_result) }}</textarea></div>
                <div><x-input-label for="is_effective" value="Conclusión"/><select id="is_effective" name="is_effective" class="mt-1 block w-full rounded-xl border-slate-300"><option value="1" @selected($case->is_effective===true)>El plan fue eficaz</option><option value="0" @selected($case->is_effective===false)>El plan no fue eficaz</option></select></div>
                <div><x-input-label for="closure_notes" value="Observaciones de cierre"/><textarea id="closure_notes" name="closure_notes" rows="2" class="mt-1 block w-full rounded-xl border-slate-300">{{ old('closure_notes',$case->closure_notes) }}</textarea></div>
                <div class="sm:col-span-2 flex justify-end"><x-primary-button>Guardar verificación</x-primary-button></div>
            </form>@else<p class="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">La verificación final la registra el coordinador o Gestión de Calidad.</p>@endif
        </section>
        @endif
        @if(!$executionOnly && $case->status !== 'closed')<section x-data="{ type: '{{ old('assignee_type','internal') }}', candidate: '', selected: @js($newActionAssigneeIds), people: @js($responsibleOptions), add() { const id=Number(this.candidate); if(id && !this.selected.includes(id)) this.selected.push(id); this.candidate=''; }, person(id) { return this.people.find(person => person.id === id) } }" class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h3 class="text-lg font-bold">Agregar acción</h3><form method="POST" action="{{ route('cases.tasks.store',$case) }}" class="mt-6 grid gap-5 sm:grid-cols-2">@csrf
            <div class="sm:col-span-2"><x-input-label for="title" value="Acción a realizar"/><x-text-input id="title" name="title" class="mt-1 block w-full" required/><x-input-error :messages="$errors->get('title')" class="mt-1"/></div>
            <div class="sm:col-span-2"><x-input-label for="description" value="Descripción"/><textarea id="description" name="description" rows="3" class="mt-1 block w-full rounded-xl border-slate-300"></textarea></div>
            <div class="sm:col-span-2"><x-input-label for="expected_result" value="Evidencia esperada (opcional)"/><textarea id="expected_result" name="expected_result" rows="2" class="mt-1 block w-full rounded-xl border-slate-300" placeholder="Ej.: acta de socialización, listado de asistencia, informe o captura del sistema"></textarea></div>
            <div><x-input-label for="assignee_type" value="Tipo de responsable"/><select id="assignee_type" name="assignee_type" x-model="type" class="mt-1 block w-full rounded-xl border-slate-300"><option value="internal">Usuario de CUMPLE</option><option value="external">Responsable externo</option></select></div>
            <div><x-input-label for="due_at" value="Fecha límite"/><x-text-input id="due_at" name="due_at" type="date" class="mt-1 block w-full" required/></div>
            <div x-show="type === 'internal'" class="sm:col-span-2"><x-input-label for="assignee_candidate" value="Usuarios responsables"/><div class="mt-1 flex flex-col gap-2 sm:flex-row"><select id="assignee_candidate" x-model="candidate" class="block min-w-0 flex-1 rounded-xl border-slate-300"><option value="">Selecciona un usuario…</option><template x-for="person in people" :key="person.id"><option :value="person.id" x-text="person.name + (person.area ? ' · '+person.area : '')"></option></template></select><button type="button" @click="add" :disabled="!candidate" class="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">Agregar responsable</button></div><div class="mt-3 flex flex-wrap gap-2"><template x-for="id in selected" :key="id"><span class="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-sm font-semibold text-emerald-800 ring-1 ring-emerald-200"><input type="hidden" name="assignee_ids[]" :value="id"><span x-text="person(id)?.name"></span><button type="button" @click="selected=selected.filter(item=>item!==id)" class="text-emerald-600 hover:text-rose-700" aria-label="Quitar responsable">×</button></span></template><p x-show="selected.length===0" class="text-sm text-amber-700">Agrega al menos un responsable.</p></div></div>
            <div x-show="type === 'external'"><x-input-label for="external_assignee_name" value="Nombre del responsable externo"/><x-text-input id="external_assignee_name" name="external_assignee_name" class="mt-1 block w-full" x-bind:required="type === 'external'"/></div>
            <div x-show="type === 'external'"><x-input-label for="external_assignee_email" value="Correo externo (opcional)"/><x-text-input id="external_assignee_email" name="external_assignee_email" type="email" class="mt-1 block w-full"/></div>
            <div><x-input-label for="priority" value="Prioridad"/><select id="priority" name="priority" class="mt-1 block w-full rounded-xl border-slate-300"><option value="medium">Media</option><option value="low">Baja</option><option value="high">Alta</option><option value="critical">Crítica</option></select></div>
            <div class="sm:col-span-2"><x-input-label for="required_resources" value="Recursos requeridos (opcional)"/><textarea id="required_resources" name="required_resources" rows="2" class="mt-1 block w-full rounded-xl border-slate-300"></textarea></div>
            <div class="sm:col-span-2 flex justify-end"><x-primary-button>Asignar acción</x-primary-button></div>
        </form></section>@endif
    </div></div>
</x-app-layout>
