<x-app-layout>
    <x-slot name="header"><div class="flex items-start justify-between gap-4"><div><p class="text-sm font-semibold text-emerald-700">{{ $case->code }}</p><h2 class="mt-1 text-2xl font-bold text-slate-900">{{ $case->title }}</h2></div><a href="{{ route('cases.index') }}" class="text-sm font-semibold text-slate-600">Volver al listado</a></div></x-slot>
    <div class="py-10"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        @if(session('status'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800 ring-1 ring-emerald-200">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-sm text-rose-800 ring-1 ring-rose-200"><p class="font-bold">Revisa los campos indicados:</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="grid gap-6 lg:grid-cols-[1.15fr_.85fr]">
            <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="grid gap-5 sm:grid-cols-2"><div><p class="text-xs font-semibold uppercase text-slate-500">Fuente</p><p class="mt-1 font-semibold">{{ $case->source->name }}</p></div><div><p class="text-xs font-semibold uppercase text-slate-500">Tipo</p><p class="mt-1">{{ $case->action_type === 'corrective' ? 'Acción correctiva' : 'Acción de mejora' }}</p></div><div><p class="text-xs font-semibold uppercase text-slate-500">Área que reporta</p><p class="mt-1">{{ $case->reportingArea->name }}</p></div><div><p class="text-xs font-semibold uppercase text-slate-500">Fecha</p><p class="mt-1">{{ $case->reported_at->format('d/m/Y') }}</p></div><div class="sm:col-span-2"><p class="text-xs font-semibold uppercase text-slate-500">Descripción</p><p class="mt-2 whitespace-pre-line leading-7 text-slate-700">{{ $case->finding_description }}</p></div></div></section>
            <aside class="rounded-2xl bg-emerald-950 p-6 text-white"><p class="text-sm font-semibold text-emerald-200">Documento institucional</p><h3 class="mt-2 text-lg font-bold">El original continúa siendo oficial</h3><p class="mt-3 text-sm leading-6 text-emerald-100">CUMPLE organiza las acciones y evidencias. Próximamente podrás adjuntar el Excel original y producir una copia de trabajo diligenciada.</p></aside>
        </div>
        <div class="grid gap-6 lg:grid-cols-2">
            <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex items-start justify-between gap-4"><div><h3 class="text-lg font-bold">Documentos institucionales</h3><p class="mt-1 text-sm text-slate-500">El original se conserva sin modificaciones.</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-700">{{ $case->documents->count() }} archivos</span></div>
                <div class="mt-5 space-y-2">@foreach($case->documents as $document)<div class="flex items-center justify-between rounded-xl border border-slate-200 p-3"><div class="min-w-0"><p class="truncate text-sm font-semibold">{{ $document->original_name }}</p><p class="text-xs text-slate-500">{{ ['original'=>'Original recibido','working'=>'Copia de trabajo','final'=>'Versión preparada'][$document->document_stage] ?? $document->document_stage }} · {{ number_format($document->size / 1024, 0) }} KB</p></div><a href="{{ route('documents.download',$document) }}" class="ml-3 text-sm font-bold text-emerald-700">Descargar</a></div>@endforeach</div>
                <form method="POST" enctype="multipart/form-data" action="{{ route('cases.documents.store',$case) }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf
                    <div class="sm:col-span-2"><x-input-label for="file" value="Adjuntar Word, Excel o PDF"/><input id="file" name="file" type="file" accept=".xlsx,.xls,.docx,.doc,.pdf" class="mt-1 block w-full text-sm" required></div>
                    <select name="document_stage" class="rounded-xl border-slate-300 text-sm"><option value="original">Original recibido</option><option value="working">Copia de trabajo</option><option value="final">Versión preparada para enviar</option></select>
                    <select name="document_type" class="rounded-xl border-slate-300 text-sm"><option value="finding_report">Reporte y plan de acción</option><option value="nonconformity">No conforme</option><option value="minutes">Acta</option><option value="other">Otro</option></select>
                    <div class="sm:col-span-2 flex justify-end"><x-secondary-button>Guardar documento</x-secondary-button></div>
                </form>
            </section>
            <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h3 class="text-lg font-bold">Priorización y validación</h3><p class="mt-1 text-sm text-slate-500">Solo se habilitará un método de análisis. INVIMA utiliza siempre causa–efecto.</p>
                <form method="POST" action="{{ route('cases.prioritization.update',$case) }}" class="mt-5 grid gap-4 sm:grid-cols-3">@csrf @method('PATCH')
                    @foreach(['urgency_score'=>'Urgencia','scope_score'=>'Alcance','evolution_score'=>'Evolución'] as $field=>$label)<div><x-input-label :for="$field" :value="$label"/><input id="{{ $field }}" name="{{ $field }}" type="number" min="0" max="10" value="{{ old($field,$case->$field) }}" class="mt-1 block w-full rounded-xl border-slate-300" required></div>@endforeach
                    <div class="sm:col-span-3"><x-input-label for="analysis_method" value="Método indicado por la priorización"/><select id="analysis_method" name="analysis_method" class="mt-1 block w-full rounded-xl border-slate-300" {{ $case->source->is_invima ? 'disabled' : '' }}><option value="five_whys" @selected($case->analysis_method==='five_whys')>Cinco por qué</option><option value="cause_effect" @selected($case->analysis_method==='cause_effect')>Causa–efecto</option></select>@if($case->source->is_invima)<input type="hidden" name="analysis_method" value="cause_effect"><p class="mt-1 text-xs font-semibold text-emerald-700">Asignado automáticamente por ser fuente INVIMA.</p>@endif</div>
                    <div class="sm:col-span-3"><x-input-label for="validation_notes" value="Observaciones de validación"/><textarea id="validation_notes" name="validation_notes" rows="2" class="mt-1 block w-full rounded-xl border-slate-300">{{ old('validation_notes',$case->validation_notes) }}</textarea></div>
                    <div class="sm:col-span-3 flex items-center justify-between"><p class="text-sm text-slate-600">Puntaje: <strong>{{ $case->priority_score ?? 'Pendiente' }}</strong></p><x-secondary-button>Guardar priorización</x-secondary-button></div>
                </form>
            </section>
        </div>
        @if($case->analysis_method)
        <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div><p class="text-sm font-semibold text-emerald-700">Método seleccionado</p><h3 class="mt-1 text-lg font-bold">{{ $case->analysis_method === 'five_whys' ? 'Análisis de los cinco por qué' : 'Análisis de causa–efecto' }}</h3></div>
            <form method="POST" action="{{ route('cases.analysis.update',$case) }}" class="mt-6 space-y-5">@csrf @method('PATCH')
                <div><x-input-label for="immediate_correction" value="Acción inmediata o corrección"/><textarea id="immediate_correction" name="immediate_correction" rows="3" class="mt-1 block w-full rounded-xl border-slate-300">{{ old('immediate_correction',$case->immediate_correction) }}</textarea></div>
                @if($case->analysis_method === 'five_whys')
                    <div class="grid gap-3">@for($i=0;$i<5;$i++)<div><x-input-label :for="'why_'.$i" :value="($i+1).'. ¿Por qué?'"/><textarea id="why_{{ $i }}" name="whys[]" rows="2" class="mt-1 block w-full rounded-xl border-slate-300" required>{{ old('whys.'.$i, data_get($case->analysis_data,'whys.'.$i)) }}</textarea></div>@endfor</div>
                @else
                    @php($categories=['Personal, habilidad o técnica','Adherencia a protocolos o guías','Comunicación, atención o conocimiento','Equipos y tecnología','Recursos e insumos','Procedimientos y documentación','Entorno e infraestructura','Supervisión, medición e indicadores'])
                    <div><x-input-label value="Categorías relacionadas"/><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach($categories as $category)<label class="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm"><input type="checkbox" name="cause_categories[]" value="{{ $category }}" class="rounded border-slate-300 text-emerald-700" @checked(in_array($category,old('cause_categories',data_get($case->analysis_data,'categories',[]))))>{{ $category }}</label>@endforeach</div></div>
                    <div><x-input-label for="cause_description" value="Descripción de las causas"/><textarea id="cause_description" name="cause_description" rows="4" class="mt-1 block w-full rounded-xl border-slate-300" required>{{ old('cause_description',data_get($case->analysis_data,'description')) }}</textarea></div>
                @endif
                <div><x-input-label for="root_cause" value="Causa raíz consolidada"/><textarea id="root_cause" name="root_cause" rows="3" class="mt-1 block w-full rounded-xl border-slate-300" required>{{ old('root_cause',$case->root_cause) }}</textarea></div>
                <div class="flex justify-end"><x-primary-button>Guardar análisis</x-primary-button></div>
            </form>
        </section>
        @endif
        <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex items-center justify-between"><div><h3 class="text-lg font-bold">Acciones del plan</h3><p class="mt-1 text-sm text-slate-500">Cada acción puede asignarse a un usuario CUMPLE o a una persona externa.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-sm font-bold text-emerald-800">{{ $case->tasks->count() }}</span></div>
            <div class="mt-5 space-y-3">@forelse($case->tasks as $task)<article x-data="{ open: false }" class="rounded-xl border border-slate-200 p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="font-bold text-slate-900">{{ $task->title }}</p><p class="mt-1 text-sm text-slate-600">Responsable: <span class="font-semibold">{{ $task->responsible_name }}</span> @if($task->assignee_type==='external')<span class="ml-1 rounded bg-violet-50 px-2 py-0.5 text-xs text-violet-700">Externo</span>@endif</p></div><div class="text-right"><p class="text-xs uppercase text-slate-500">Fecha límite</p><p class="font-semibold {{ $task->due_at?->isPast() && $task->status!=='completed' ? 'text-rose-700' : 'text-slate-800' }}">{{ $task->due_at?->format('d/m/Y') }}</p><button @click="open=!open" type="button" class="mt-2 text-xs font-bold text-emerald-700">Seguimiento y evidencias</button></div></div>
                <div x-show="open" x-cloak class="mt-4 grid gap-4 border-t border-slate-100 pt-4 lg:grid-cols-2"><form method="POST" action="{{ route('tasks.update',$task) }}" class="space-y-3">@csrf @method('PATCH')<div class="grid grid-cols-2 gap-3"><select name="status" class="rounded-xl border-slate-300 text-sm">@foreach(['pending'=>'Sin inicio','in_progress'=>'En proceso','in_review'=>'En revisión','completed'=>'Cerrada','cancelled'=>'Cancelada'] as $value=>$label)<option value="{{ $value }}" @selected($task->status===$value)>{{ $label }}</option>@endforeach</select><input name="progress" type="number" min="0" max="100" value="{{ $task->progress }}" class="rounded-xl border-slate-300 text-sm" aria-label="Porcentaje de avance"></div><textarea name="review_notes" rows="2" class="block w-full rounded-xl border-slate-300 text-sm" placeholder="Nota de seguimiento">{{ $task->review_notes }}</textarea><x-secondary-button>Actualizar</x-secondary-button></form>
                <div><form method="POST" enctype="multipart/form-data" action="{{ route('tasks.evidence.store',$task) }}" class="space-y-3">@csrf<input name="evidence" type="file" class="block w-full text-sm" required><input name="description" class="block w-full rounded-xl border-slate-300 text-sm" placeholder="Descripción de la evidencia"><x-secondary-button>Adjuntar evidencia</x-secondary-button></form><div class="mt-3 space-y-1">@foreach($task->evidences as $evidence)<a href="{{ route('evidence.download',$evidence) }}" class="block truncate text-sm font-semibold text-emerald-700">{{ $evidence->original_name }}</a>@endforeach</div></div></div>
            </article>@empty<div class="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">Aún no se han agregado acciones.</div>@endforelse</div>
        </section>
        <section x-data="{ type: '{{ old('assignee_type','internal') }}' }" class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h3 class="text-lg font-bold">Agregar acción</h3><form method="POST" action="{{ route('cases.tasks.store',$case) }}" class="mt-6 grid gap-5 sm:grid-cols-2">@csrf
            <div class="sm:col-span-2"><x-input-label for="title" value="Acción a realizar"/><x-text-input id="title" name="title" class="mt-1 block w-full" required/><x-input-error :messages="$errors->get('title')" class="mt-1"/></div>
            <div class="sm:col-span-2"><x-input-label for="description" value="Descripción"/><textarea id="description" name="description" rows="3" class="mt-1 block w-full rounded-xl border-slate-300"></textarea></div>
            <div><x-input-label for="assignee_type" value="Tipo de responsable"/><select id="assignee_type" name="assignee_type" x-model="type" class="mt-1 block w-full rounded-xl border-slate-300"><option value="internal">Usuario de CUMPLE</option><option value="external">Responsable externo</option></select></div>
            <div><x-input-label for="due_at" value="Fecha límite"/><x-text-input id="due_at" name="due_at" type="date" class="mt-1 block w-full" required/></div>
            <div x-show="type === 'internal'"><x-input-label for="assigned_to" value="Usuario responsable"/><select id="assigned_to" name="assigned_to" class="mt-1 block w-full rounded-xl border-slate-300"><option value="">Seleccione…</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}{{ $user->area ? ' · '.$user->area->name : '' }}</option>@endforeach</select></div>
            <div x-show="type === 'external'"><x-input-label for="external_assignee_name" value="Nombre del responsable externo"/><x-text-input id="external_assignee_name" name="external_assignee_name" class="mt-1 block w-full"/></div>
            <div x-show="type === 'external'"><x-input-label for="external_assignee_email" value="Correo externo (opcional)"/><x-text-input id="external_assignee_email" name="external_assignee_email" type="email" class="mt-1 block w-full"/></div>
            <div><x-input-label for="priority" value="Prioridad"/><select id="priority" name="priority" class="mt-1 block w-full rounded-xl border-slate-300"><option value="medium">Media</option><option value="low">Baja</option><option value="high">Alta</option><option value="critical">Crítica</option></select></div>
            <div class="sm:col-span-2"><x-input-label for="required_resources" value="Recursos requeridos (opcional)"/><textarea id="required_resources" name="required_resources" rows="2" class="mt-1 block w-full rounded-xl border-slate-300"></textarea></div>
            <div class="sm:col-span-2 flex justify-end"><x-primary-button>Asignar acción</x-primary-button></div>
        </form></section>
    </div></div>
</x-app-layout>
