<x-app-layout>
    <x-slot name="header"><div class="flex items-start justify-between gap-4"><div><p class="text-sm font-semibold text-emerald-700">{{ $case->code }}</p><h2 class="mt-1 text-2xl font-bold text-slate-900">{{ $case->title }}</h2></div><a href="{{ route('cases.index') }}" class="text-sm font-semibold text-slate-600">Volver al listado</a></div></x-slot>
    <div class="py-10"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        @if(session('status'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800 ring-1 ring-emerald-200">{{ session('status') }}</div>@endif
        <div class="grid gap-6 lg:grid-cols-[1.15fr_.85fr]">
            <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="grid gap-5 sm:grid-cols-2"><div><p class="text-xs font-semibold uppercase text-slate-500">Fuente</p><p class="mt-1 font-semibold">{{ $case->source->name }}</p></div><div><p class="text-xs font-semibold uppercase text-slate-500">Tipo</p><p class="mt-1">{{ $case->action_type === 'corrective' ? 'Acción correctiva' : 'Acción de mejora' }}</p></div><div><p class="text-xs font-semibold uppercase text-slate-500">Área que reporta</p><p class="mt-1">{{ $case->reportingArea->name }}</p></div><div><p class="text-xs font-semibold uppercase text-slate-500">Fecha</p><p class="mt-1">{{ $case->reported_at->format('d/m/Y') }}</p></div><div class="sm:col-span-2"><p class="text-xs font-semibold uppercase text-slate-500">Descripción</p><p class="mt-2 whitespace-pre-line leading-7 text-slate-700">{{ $case->finding_description }}</p></div></div></section>
            <aside class="rounded-2xl bg-emerald-950 p-6 text-white"><p class="text-sm font-semibold text-emerald-200">Documento institucional</p><h3 class="mt-2 text-lg font-bold">El original continúa siendo oficial</h3><p class="mt-3 text-sm leading-6 text-emerald-100">CUMPLE organiza las acciones y evidencias. Próximamente podrás adjuntar el Excel original y producir una copia de trabajo diligenciada.</p></aside>
        </div>
        <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex items-center justify-between"><div><h3 class="text-lg font-bold">Acciones del plan</h3><p class="mt-1 text-sm text-slate-500">Cada acción puede asignarse a un usuario CUMPLE o a una persona externa.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-sm font-bold text-emerald-800">{{ $case->tasks->count() }}</span></div>
            <div class="mt-5 space-y-3">@forelse($case->tasks as $task)<article class="rounded-xl border border-slate-200 p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="font-bold text-slate-900">{{ $task->title }}</p><p class="mt-1 text-sm text-slate-600">Responsable: <span class="font-semibold">{{ $task->responsible_name }}</span> @if($task->assignee_type==='external')<span class="ml-1 rounded bg-violet-50 px-2 py-0.5 text-xs text-violet-700">Externo</span>@endif</p></div><div class="text-right"><p class="text-xs uppercase text-slate-500">Fecha límite</p><p class="font-semibold {{ $task->due_at?->isPast() ? 'text-rose-700' : 'text-slate-800' }}">{{ $task->due_at?->format('d/m/Y') }}</p></div></div></article>@empty<div class="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">Aún no se han agregado acciones.</div>@endforelse</div>
        </section>
        <section x-data="{ type: '{{ old('assignee_type','internal') }}' }" class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h3 class="text-lg font-bold">Agregar acción</h3><form method="POST" action="{{ route('cases.tasks.store',$case) }}" class="mt-6 grid gap-5 sm:grid-cols-2">@csrf
            <div class="sm:col-span-2"><x-input-label for="title" value="Acción a realizar"/><x-text-input id="title" name="title" class="mt-1 block w-full" required/><x-input-error :messages="$errors->get('title')" class="mt-1"/></div>
            <div class="sm:col-span-2"><x-input-label for="description" value="Descripción"/><textarea id="description" name="description" rows="3" class="mt-1 block w-full rounded-xl border-slate-300"></textarea></div>
            <div><x-input-label for="assignee_type" value="Tipo de responsable"/><select id="assignee_type" name="assignee_type" x-model="type" class="mt-1 block w-full rounded-xl border-slate-300"><option value="internal">Usuario de CUMPLE</option><option value="external">Responsable externo</option></select></div>
            <div><x-input-label for="due_at" value="Fecha límite"/><x-text-input id="due_at" name="due_at" type="date" class="mt-1 block w-full" required/></div>
            <div x-show="type === 'internal'"><x-input-label for="assigned_to" value="Usuario responsable"/><select id="assigned_to" name="assigned_to" class="mt-1 block w-full rounded-xl border-slate-300"><option value="">Seleccione…</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}{{ $user->area ? ' · '.$user->area->name : '' }}</option>@endforeach</select></div>
            <div x-show="type === 'external'"><x-input-label for="external_assignee_name" value="Nombre del responsable externo"/><x-text-input id="external_assignee_name" name="external_assignee_name" class="mt-1 block w-full"/></div>
            <div x-show="type === 'external'"><x-input-label for="external_assignee_email" value="Correo externo (opcional)"/><x-text-input id="external_assignee_email" name="external_assignee_email" type="email" class="mt-1 block w-full"/></div>
            <div><x-input-label for="priority" value="Prioridad"/><select id="priority" name="priority" class="mt-1 block w-full rounded-xl border-slate-300"><option value="medium">Media</option><option value="low">Baja</option><option value="high">Alta</option><option value="critical">Crítica</option></select></div>
            <div class="sm:col-span-2"><x-input-label for="required_resources" value="Recursos requeridos (opcional)"/><textarea id="required_resources" name="required_resources" rows="2" class="mt-1 block w-full rounded-xl border-slate-300"></textarea></div>
            <div class="sm:col-span-2 flex justify-end"><x-primary-button>Asignar acción</x-primary-button></div>
        </form></section>
    </div></div>
</x-app-layout>
